### ISSUE TITLE
wxGTK 3.0: columns are right-aligned instead of left-aligned

### ISSUE THREAD

**Issue by rffontenelle** [vslavik/poedit#369] opened 2017-03-30 16:52 UTC
Brazilian Portuguese (pt_BR) uses left-to-right text, which currently doesn't happen. Also, I'd expect 'ID' column to be in the left side (not sure if that's intentional). Please let me know if you need any (and which) debug info.

![captura de tela de 2017-03-30 13-37-18](https://cloud.githubusercontent.com/assets/1571783/24515976/92a4058a-154f-11e7-86a5-2e331b525c7f.png)

**Comment by vslavik** [comment] 2017-03-30 16:56
Basic, *always* required information is specification of the build, platform, version, all involved files, step by step instructions to reproduce.

I very much doubt this is about pt_BR specifically; I rather suspect another wxGTK issue. Please verify, i.e. try a) running under different locales and b) opening files in different languages.

This doesn't appear to be RTL, by the way — the text isn't rendered the way it would in that case.

**Comment by rffontenelle** [comment] 2017-03-30 23:45
> Basic, always required information is specification of the build, platform, version, all involved files, step by step instructions to reproduce.

**Distro**: Arch Linux 64-bit
**Package versions:**
 poedit 2.0
 wxgtk 3.1.0 (built with GTK+2)

**Steps to reproduce:** Open existing PO file, or create from POT

**Files involved:** Any PO file I opened so far in this version of poedit

> I very much doubt this is about pt_BR specifically; I rather suspect another wxGTK issue. Please verify, i.e. try a) running under different locales and b) opening files in different language

You're right. I opened about half of the locales available for poedit and _all_ of them have the same text alignment as pt_BR

I tested the following locales in UTF8: an_ES ar_BH az_AZ be_BY be_BY@latin bg_BG bs_BA ca_ES cs_CZ da_DK de_DE el_GR en_GB en_US es_ES et_EE eu_ES fa_IR fi_FI fr_FR ga_IE gl_ES he_IL hr_HR hu_HU hy_AM id_ID is_IS it_IT ja_JP ko_KR pt_BR uz_UZ vi_VN zh_CN zh_TW

> This doesn't appear to be RTL, by the way — the text isn't rendered the way it would in that case.

Right, sorry. What I meant is the text right-aligned for msgid and msgstr (e.g. the highlighted text)

**Comment by vslavik** [comment] 2017-03-31 08:31
> I tested the following locales in UTF8: an_ES ar_BH az_AZ be_BY be_BY@latin bg_BG bs_BA ca_ES cs_CZ da_DK de_DE el_GR en_GB en_US es_ES et_EE eu_ES fa_IR fi_FI fr_FR ga_IE gl_ES he_IL hr_HR hu_HU hy_AM id_ID is_IS it_IT ja_JP ko_KR pt_BR uz_UZ vi_VN zh_CN zh_TW

Thanks for confirming — but **wow**, talk about thorough testing. Thanks!

> Right, sorry. 

No need at all, I was just clarifying that, more to myself/record really, to avoid going a wrong path looking for the cause.

**Comment by vslavik** [comment] 2017-04-04 12:51
The bug is fixed (in wxGTK-3.0.x) in https://github.com/wxWidgets/wxWidgets/commit/ed8c3feab389493429c0a9bdde832b51a1c2186a

I don't see a way to work around it in Poedit code just yet.

**Comment by vslavik** [comment] 2017-04-04 14:01
I'm sorry, I misread you, I now see that you say this is with 3.1.0 — I can indeed *not* reproduce with 3.0.2. 

If you can reproduce with 3.0.2, I'll try to find some workaround. But since this is fixed in wx master (i.e. what supersedes 3.1.0 unstable release) as well as 3.0 branch (to be 3.0.3 if it ever happens), there's little point in spending time on this — if, again, it doesn't exhibit itself with 3.0.2.

**Comment by rffontenelle** [comment] 2017-04-04 14:11
I didn't mention wxgtk 3.0.2 (which is the current version in provided in Arch Linux) because I'm not able to use poedit 2.0.0 built against it as commented on #366 - just to remind you that I built 3.1.0 locally to test poedit.

**Comment by vslavik** [comment] 2017-04-05 08:21
(With latest Poedit master you should be able to build against wxGTK 3.0.2 and check this behavior too,  if you want (after ignoring the one unrelated assert from #366). But since that assert needs a wxGTK patch to fix anyway, perhaps it doesn't matter, as the above patch could be applied as well.)

**Comment by vslavik** [comment] 2017-04-10 17:01
Closing because it seems to only affect an old unstable wx release.

**Closed by vslavik** 2017-04-10 17:01 UTC
Labels: Linux

**Comment by JSteunou** [comment] 2017-06-14 10:27
Not that old, it's on the last ubuntu release. Is there something I can do to fix it on my ubuntu desktop?

**Comment by vslavik** [comment] 2017-06-14 16:00
@JSteunou No, it *is* old, and it is not true that Ubuntu packages unstable wxGTK series. I think you didn't read the *content* of this issue carefully enough and confuse this with 3.0.2 — for which there *is* a separate bug, linked just above, with all the explanations you may need.

**Comment by JSteunou** [comment] 2017-06-15 08:08
issue #366 is about poedit not working at all, my issue is about poedit having all the thing right align like @rffontenelle snapshot 

I think I'm on the correct issue.

I dont know which version of wxGTK I have, I know I have Ubuntu 17.04, but as it's seems to be the same bug and 17.04 is the latest Ubuntu release, I am surprised this issue is closed because of *old unstable release*. Is Ubuntu packager used an *old unstable release*? Can I update it or do something to solve this issue on my desktop?

**Comment by vslavik** [comment] 2017-06-15 08:17
> I am surprised

That would be because you didn't actually *read* this issue — yet you are so certain you're right despite not even having any clue about the primary aspect, i.e. which wxGTK version you have. Either wait for packaged version of Poedit or use Poedit 2.0.2, which has correct dependencies to avoid both this and #366. In any case, please stop adding any more comment noise to this issue.

**Comment by JSteunou** [comment] 2017-06-15 09:41
I was just asking nicely a little help about how I can fix *this* bug on my desktop (because this **is** the bug I have and every Ubuntu user have), as this issue is closed, hence resolve... but yeah I will just *stop adding any more noise*.
