### ISSUE TITLE
Crowdin: Only translated strings are shown

### ISSUE THREAD

**Issue by tastytea** [vslavik/poedit#697] opened 2021-05-23 09:31 UTC
Version: 2.4.3
OS: Gentoo Linux

I wanted to use Poedit with <https://crowdin.com/project/factorio-mods-localization> but it only shows strings that are already translated. The untranslated strings are not shown.

*Edit: It does seem to be specific to the project, with <https://crowdin.com/project/lets-encrypt-website> all strings are shown.*

**Comment by vslavik** [comment] 2021-05-23 09:58
Please read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (which GitHub asked you to do when you created this issue), follow the instructions therein and provide the missing *precise* reproduction instructions. Thanks!

**Comment by tastytea** [comment] 2021-05-23 10:08
To reproduce:

* Join <https://crowdin.com/project/factorio-mods-localization>
* Open Poedit
* Click File → Open From Crowdin…
* Select Project: “Factorio mods localization”, Language: German
* Select brush-tools.ini
* Compare with <https://crowdin.com/translate/factorio-mods-localization/922/en-de>

Nothing is shown in Poedit, except “There are no translations. That's unusual.“ The file has 26 untranslated strings on the website.

**Comment by vslavik** [comment] 2021-05-27 10:36
As of now, there are still some untranslated strings in that file, but most are translated, so the “There are no translations. That's unusual.“ thing doesn't happen. However I can confirm that the remaining untranslated strings don't show in Poedit.

This seems to be a bug in Crowdin API, or the discrepancy vs the docs.

I reproduced the steps with a logging proxy and can see that Poedit makes a requests to the file via `https://crowdin.com/api/v2/projects/307377/translations/builds/files/922`, sending
```json
{
	"exportAsXliff": true,
	"targetLanguageId": "de"
}
```
The response file does *not* contain the untranslated strings — i.e. Poedit faithfully shows what Crowdin sent. The endpoint is [documented](https://support.crowdin.com/api/v2/#operation/api.projects.translations.builds.files.post) as including untranslated strings by default. It seems that it now requires an explicit `"skipUntranslatedStrings": false` parameter to restore that behavior; I *think* it must have changed at some point.

Thanks a lot for spotting the bug and giving me a precise steps I could follow! Fix is incoming.

**Closed** 2021-05-27 11:07 UTC
