### ISSUE TITLE
Support file references with spaces surrounded by U+2068/U+2069

### ISSUE THREAD

**Issue by tomchen** [vslavik/poedit#706] opened 2021-07-09 17:44 UTC
To reproduce:

In an empty test folder, create two subfolders named `folder name with space` and `folder name with space 2`, both subfolders have a same text file `a.py` with the content:

```py
_('aa')
```

Use Poedit to create a new translation of any language, save, then "Extract from source", then set the root test folder as the path, OK.

Right click the "aa" string, you'll find Poedit unable to handle path containing space correctly.

![2021-07-09_193412](https://user-images.githubusercontent.com/529949/125116293-d081c000-e0ec-11eb-932b-bff1c09def4e.png)

In the code occurrences comment block in .po files, a space could be considered as both separator, and space in the path. Poedit doesn't know what to do with the space, which results in the problem.

The problem exists in both v2 and v3.

**Comment by vslavik** [comment] 2021-07-09 18:06
The PO file format spec — which does not originate with Poedit, but GNU gettext, and so is not something Poedit can affect — doesn't allow for filenames with spaces, and it is therefore impossible to unambiguously parse such references.

If you feel handling this is important, please submit a PR that implements reasonable heuristic to improve the handling; I'd be happy to accept it.

I'm closing this issue, because it's not a bug and not something *I* am going to add a heuristic for (my opinion on the subject is simple: don't use spaces in source code paths).

**Comment by vslavik** [comment] 2021-07-18 16:52
Reopening: Upcoming GNU gettext [clarifies the behavior](https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=NEWS;h=9ca0dbc401183af9edf9f27f6150b0ed6c8d5a6a;hb=refs/heads/master):
```
 * PO file format:
      - When a #: line contains references to file names that contain spaces,
        these file names are surrounded by Unicode characters U+2068 and U+2069.
        This makes it possible to parse such references correctly.
```
Once this is released and `xgettext` supports generates, Poedit should recognize it.

**Comment by vslavik** [comment] 2023-06-17 18:00
> Once this is released and xgettext supports generates, Poedit should recognize it.

gettext-0.22 was released today with support.

**Closed** 2023-09-23 16:51 UTC
