### ISSUE TITLE
Can't authenticate with poedit behind corporate proxy

### ISSUE THREAD

**Issue by tomolimo** [vslavik/poedit#276] opened 2016-06-09 08:04 UTC
Hello,

In reference to #217: 
I've got exactly the same problem, and here is the screen copy of the dialog box resulting of the 'authorize' button in crowdin:

![image](https://cloud.githubusercontent.com/assets/7569958/15922700/78d84cfa-2e29-11e6-954a-14a1134990cd.png)

What I know is that URL with protocols other than HTTP(s) are rejected by our corporate proxy.

Could it be possible to have an HTTPS:// instead of POEDIT://?

Thank you,
Regards,
Tomolimo

**Comment by c72578** [comment] 2016-06-09 08:30
What happens, when you click on the button "Launch Application"?

**Comment by tomolimo** [comment] 2016-06-09 08:33
It goes back to the poedit application and 'Updating user information' is still waiting till a timeout

![image](https://cloud.githubusercontent.com/assets/7569958/15923436/7a2de1a6-2e2d-11e6-85fa-7cebe8edd37b.png)

Is there any logs which I can search in?

**Comment by tomolimo** [comment] 2016-06-09 09:51
During this, if I click on 'OK', an try to 'Collaborate on a translation with others' I get:

![image](https://cloud.githubusercontent.com/assets/7569958/15925675/6b302050-2e38-11e6-8035-2c7979d97db9.png)


And after some times I get the timeout:

![image](https://cloud.githubusercontent.com/assets/7569958/15925691/7e6eebf6-2e38-11e6-8b94-3a439feffae2.png)

**Comment by vslavik** [comment] 2016-06-10 16:59
> I've got exactly the same problem

Then please add to an existing issue instead of creating an unnecessary duplicate. 

> Could it be possible to have an HTTPS:// instead of POEDIT://?

No. It’s calling back to the application, it needs to *open the application* and can’t very well offload that to web. Plain HTTP would be possible, at the cost of much higher complexity (Poedit would need to embed a web server in itself), HTTPS not in any way remotely acceptable — and the same picky corporate nonsense that blocks Crowdin now would probably block that as well.

> > What happens, when you click on the button "Launch Application”?
> It goes back to the poedit application and 'Updating user information' is still waiting till a timeout

Thus demonstrating that the use of a custom protocol is *not* the problem — otherwise it wouldn’t go back to the application. 

At first glance, this seems to either be a transient error (network connectivity problem, Crowdin briefly down, etc.) or some less-than-good firewall rule dumping the connection improperly (i.e. timing it out, instead of dropping and causing a clear error). Can you try again? 

If it’s persistent, could it be that you have the proxy misconfigured on your computer? I.e. do suggestions work? If they do, but this doesn’t, could your IT department check their logs to see what specifically is being blocked?

Thanks!

**Comment by tomolimo** [comment] 2016-06-13 06:58
> > I've got exactly the same problem
> (Then please add to an existing issue instead of creating an unnecessary duplicate in the future.)

As the issue was closed I preferred to post a new one, sorry for that.

> > Could it be possible to have an HTTPS:// instead of POEDIT://?
> No. It’s calling back to the application, it needs to open the application and can’t very well offload that to web. Plain HTTP would be possible, at the cost of much higher complexity (Poedit would need to embed a web server in itself), HTTPS not in any way remotely acceptable — and the same picky corporate nonsense that blocks Crowdin now would probably block that as well.

I made some more investigations I saw that there is no link with the trouble itself (as you wrote).

> At first glance, this seems to either be a transient error (network connectivity problem, Crowdin briefly down, etc.) or some less-than-good firewall rule dumping the connection improperly (i.e. timing it out, instead of dropping and causing a clear error). Can you try again?

> If it’s persistent, could it be that you have the proxy misconfigured on your computer? I.e. do suggestions work? If they do, but this doesn’t, could your IT department check their logs to see what specifically is being blocked?

I made a test at home (not being behind our corporate proxy/firewall), and "tada": the connection was perfect :smile: .

I'm going to check this issue with the network people and keep you informed.

Thank you,
regards,
Tomolimo

**Comment by tomolimo** [comment] 2016-06-13 07:16
Juste one more question when poedit is requesting the project list, language, and file from crowdin: 
![image](https://cloud.githubusercontent.com/assets/7569958/15999645/6876a85e-3147-11e6-8193-3a69243a8b4a.png)

which URI is used? I'm trying to spy that with Wireshark and can't see the network request.
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment] 2016-06-13 08:18
I tried also to spy network traffic with fiddler and I got nothing for the 'open crowdin translation' like if this request was not using proxy settings, and such I'm not able to capture it. I tried with the 'check update', and there I can capture network traffic,...

**Comment by vslavik** [comment] 2016-06-13 09:32
> I made a test at home (not being behind our corporate proxy/firewall), and "tada": the connection was perfect 😄 .

Not terribly surprising: it’s obvious from both issues that it is proxy-related.

> which URI is used?

If you want to know the exact URL, check the source code. But the error itself tells you it’s a *HTTP* error. This really has nothing to do with the `poedit://` protocol handler.

> I tried also to spy network traffic with fiddler and I got nothing for the 'open crowdin translation' like if this request was not using proxy settings, and such I'm not able to capture it.

Because something is obviously blocking (but, weirdly, not *dropping*) the TCP connection. That’s what the error says: you got a *timeout*.

> I tried with the 'check update', and there I can capture network traffic,…

That’s not very relevant, it’s an unrelated piece of code. What would be much more useful is an answer to my question above: **Do translation suggestions work in Poedit behind the proxy? Yes or no?**

However, that WinSparkle updates work would suggests that the answer is that no, they don’t work either, and the cause would then be your misconfigured Windows OS where your IT department didn’t properly configure the proxy. WinSparkle uses WinInet (i.e. the same thing IE uses), Poedit itself uses WinHTTP (what .NET uses) and the two don’t share proxy settings.

See here for how to configure proxy for all Windows subsystems:
http://superuser.com/questions/489527/how-can-i-configure-proxy-settings-for-all-apps-system-ie-etc

**Comment by tomolimo** [comment] 2016-06-13 09:48
Hello,
Thank you for your answer,
Here are the answers to yours:
> Do translation suggestions work in Poedit behind the proxy? Yes or no?
![image](https://cloud.githubusercontent.com/assets/7569958/16003287/2535a7ba-315c-11e6-8a27-6d66d6831128.png)
So it seems that 'translation suggestions' are working?

I'l going to have a deep look at the links you sent about WinHTTP

**Comment by vslavik** [comment] 2016-06-13 09:54
> So it seems that 'translation suggestions' are working?

Inconclusive. These are from your *local TM*, I’m interested in online suggestions — the ones with different icons next to them. Try making the window larger to see them, going to some entry that doesn’t have so many local hits or temporarily disabling local TM in Preferences (uncheck TM→Use translation memory).

**Comment by tomolimo** [comment] 2016-06-13 10:00
You are right as soon as I've de-activated TM suggestions, then the list is empty

**Comment by tomolimo** [comment] 2016-06-13 10:01
then online suggestions are NOT working, let's try to set WinHTTP proxy

**Comment by vslavik** [comment] 2016-06-13 10:01
> You are right as soon as I've de-activated TM suggestions, then the list is empty

If there’s the same problem, it will show an error after about the same time the Crowdin window did. Please check if that’s the case (w/o moving to another entries).

**Comment by tomolimo** [comment] 2016-06-13 10:03
I had to activate online suggestions (PRO version?), and I got the timeout error:
![image](https://cloud.githubusercontent.com/assets/7569958/16003813/de21984a-315e-11e6-98da-f3e76b7b24c9.png)

**Comment by vslavik** [comment] 2016-06-13 10:09
> I had to activate

I didn’t realize (you didn’t mention this somewhat important detail) that you manually disabled them… 

Whatever the problem is (my bet is indeed on misconfigured proxy), the problem is that you have non-functional TCP networking stack in your OS. And the network is setup rather crappily, if I may say so: timeouts are the worst possible way of blocking connections, because they are slow to resolve on the client side. Other proxies that I’m aware of case “WinHttpSendRequest: 12029: A connection with the server could not be established” instead, which is something more easily recognized as a proxy failure.

**Comment by tomolimo** [comment] 2016-06-13 10:12
they were disabled by default :smile: 

But anyway I tried the `netsh winhttp import proxy source =ie` but it does nothing more

**Comment by tomolimo** [comment] 2016-06-13 10:24
I've activated the traces like this:

  Current WinHTTP Tracing settings:

    Tracing is enabled.

    Trace File Prefix: c:\temp\traceHTTP
    Trace Output: debugger
    Trace Level:  verbose (headers, APIs, and entity body)
    Network Traffic Format: hex
    Maximum size of trace file (in bytes): 512000

Restarted poedit, but got nothing more than the usual timeout and no traces at all!

**Comment by vslavik** [comment] 2016-06-13 10:38
> they were disabled by default 😄

No, they were not. You must have disabled them and forgot about it, then.

> But anyway I tried the netsh winhttp import proxy source =ie but it does nothing more

Please provide conclusive evidence that you have in fact configured WinHTTP proxy and that its settings are identical to IE *and* that both IE and other WinHTTP (e.g. .NET) applications work for you. Saying “does nothing more” is a bit short on factual information. 

Probably best if you involve your IT department. There *is* something wrong with your OS, e.g. a misconfigured firewall or something. Poedit uses a standard Windows API for network connections and this API — out of Poedit’s control — returns timeout errors. *Something is blocking Poedit’s connections*. I don’t know what or why, only you / your IT can know that.

**Comment by tomolimo** [comment] 2016-06-13 10:56
I found something that can be interesting: there are two different proxies for WinHTTP communications: one for 32bits applications and one for 64bits applications.

So I set the WinHTTP proxy for 32bits applications too (to be like IE settings) to use Fiddler as proxy.

And then I restarted poedit, and I saw the network traffic in Fiddler ('online suggestions' and also 'crowdin' communications). :smile: 
![image](https://cloud.githubusercontent.com/assets/7569958/16005108/c26c77f8-3165-11e6-8214-d48db2bd2ed6.png)

and 

![image](https://cloud.githubusercontent.com/assets/7569958/16005140/eb393cc0-3165-11e6-8468-4e270d2a3dd0.png)

**Comment by vslavik** [comment] 2016-06-13 11:02
Closing as not Poedit bug, but misconfigured proxy, then.

**Comment by tomolimo** [comment] 2016-06-13 11:04
Yes, but still have this 
![image](https://cloud.githubusercontent.com/assets/7569958/16005376/4712f9fe-3167-11e6-893f-eff67717fdd3.png)
which never ends :)

**Comment by vslavik** [comment] 2016-06-13 11:05
Probably some artifact of your screwed up network stack. Try signing out and signing back in (while with functional network connectivity).

**Comment by tomolimo** [comment] 2016-06-13 11:53
I did, but still the same problem!

**Comment by vslavik** [comment] 2016-06-13 11:58
You have to go back to Poedit, i.e. click its window, and give it a chance to refresh itself. If that does nothing, probably still some issue with your network.

**Comment by tomolimo** [comment] 2016-06-13 12:31
I found this very interesting Microsoft blog: https://blogs.msdn.microsoft.com/ieinternals/2013/10/11/understanding-web-proxy-configuration/
written by the WinHTTP's proxy code owner itself:
Which explains that WinHTTP should be used normally for services and not for applications, and if used for applications, it explains that these applications should post proxy information to the WinHTTP stack:

> ### WinHTTP Considerations
> _Thanks to Eric Loewenthal, owner of WinHTTP’s proxy code, for providing the expertise for this section_
> 
> The WinHTTP stack was designed for use in services and other contexts where WinINET would be inappropriate (e.g. because WinINET may show UI or not scale well for unattended use). WinHTTP offers a limited subset of proxy support– generally speaking, the calling code is expected to set the proxy configuration settings directly on the session or request objects. The user may attempt to configure the “default” proxy for WinHTTP using the proxycfg.exe (XP) or netsh.exe (Vista+) tools, but these tools only support fixed proxy settings (not autodetection or PAC script URLs) and WinHTTP-based applications may or may not use those settings.
> 
> The configuration tools were primarily intended or WinHTTP apps that are running as System (without a user to impersonate). 
> 
> Well-written WinHTTP apps will:
> 
> 1. If not running in a user’s process, impersonate a user
> 1. Call WinHttpGetIEProxyConfigForCurrentUser
> 1. Plug the returned settings into WinHttpGetProxyForUrl

> [Sample code for this technique](http://code.msdn.microsoft.com/windowsdesktop/WinHTTP-proxy-sample-eea13d0c) can be downloaded from MSDN. 
> 
> Note: WinHTTP will not process a proxy script if the Content-Type response header is not “application/x-ns-proxy-autoconfig” or the URL’s file extension is not one of .js, .pac, or .dat. Also, remember that WinHTTP will not use proxy script files from file:// URLs, on any version of Windows.
> 


It would be a good idea to add this settings to poedit to respect what is explained here.

Thank you for your help,
Regards,
Tomolimo

**Comment by vslavik** [comment] 2016-06-13 14:19
Hmm, that actually sounds doable even with C++ REST SDK API (WinHTTP use is internal to it and I can’t access its use of `WinHttpGetProxyForUrl` directly). Thanks!

**Comment by tomolimo** [comment] 2016-06-13 14:25
You're welcome,

**Comment by ItielMaN** [comment] 2016-06-13 16:14
Sorry for butting in, but the issue tomolimo [described before](https://github.com/vslavik/poedit/issues/276#issuecomment-225551258) happens also to me.
Tried disconnecting, reconnecting multiple times- nothing. Have no proxy. Disabled my COMODO Firewall for a while and tried again, still loading forever. This happens from when I first installed Poedit.
Don't have any more info for troubleshooting so.. tell me what else do you need.

Do I need to open a new issue for that? This doesn't seem the right place.

**Comment by vslavik** [comment] 2016-06-19 08:28
Can you please try this build: https://jumpshare.com/v/nDAdWSIYsQQ1jyLrJEGT (replace `Poedit.exe` in installed version with the one from the ZIP) and see if it correctly autodetects your proxy settings? If it doesn’t, could you show me (here or privately) your proxy settings in IE?

**Comment by tomolimo** [comment] 2016-06-20 08:10
Hello,
Here is the result: when using the new Poedit, I get this when trying to collaborate:
![image](https://cloud.githubusercontent.com/assets/7569958/16187132/dbdf2f14-36ce-11e6-964c-8a3bb61cdc87.png)
and this when openning 'preferences > accounts'
![image](https://cloud.githubusercontent.com/assets/7569958/16187146/f059a118-36ce-11e6-953a-39aea0037776.png)

and here are my proxy settings:

![image](https://cloud.githubusercontent.com/assets/7569958/16187179/1f6fa8e4-36cf-11e6-8147-96dbbd547814.png)

regards,
Tomolimo

**Comment by vslavik** [comment] 2016-06-20 08:19
With regards to proxy behavior, please limit the description to how the sidebar online suggestions behave for simplicity. It’s not clear to me from your latest comment what/if/how actually changed. I *think* you mean the kind of error changed, but I’m not sure.

**Comment by tomolimo** [comment] 2016-06-20 08:21
![image](https://cloud.githubusercontent.com/assets/7569958/16187466/c365c93c-36d0-11e6-8693-eab1d0c57471.png)

**Comment by vslavik** [comment] 2016-06-20 08:34
Returning to manual proxy setup, you wrote this:
> But anyway I tried the netsh winhttp import proxy source =ie but it does nothing more
Could you be more specific about the “does nothing more” bit? What was the output? Note also that the space before `=` shouldn’t be there, it should be `winhttp import proxy source=ie`.

Afterwards, what’s the output of `netsh winhttp show proxy`?

And if you try to manually set the proxy with `netsh winhttp set proxy proxyar.ar.ray.group:8080`? (Making sure how it behaves would probably require using the original `Poedit.exe` to rule out any interference.)

Right now, my best guess is that you’re using a *SOCKS* proxy and not a HTTP one (because a) importing from IE didn’t work, b) the same proxy is set for multiple protocols in your UI settings and c) the “Open failed” error looks like a low-level protocol failure) — do you know if that’s the case? 

If yes, this could work (again, with vanilla Poedit 1.8.8):

`netsh winhttp set proxy proxy-server="socks=proxyar.ar.ray.group:8080”`

**Comment by tomolimo** [comment] 2016-06-20 09:01
Hello

> Returning to manual proxy setup, you wrote this:

> > But anyway I tried the netsh winhttp import proxy source =ie but it does nothing more
> > Could you be more specific about the “does nothing more” bit? What was the output? Note also that the space before = shouldn’t be there, it should be winhttp import proxy source=ie.

> Afterwards, what’s the output of netsh winhttp show proxy?

The space you mentioned is not a problem I made tests with and without, and at the end the settings are the same.

What you missed is the fact that my Windows is Win7 64bits. So using the default netsh (which is the 64bits version) will set the proxy for 64bits applications (which obviously is not the case of Poedit). https://github.com/vslavik/poedit/issues/276#issuecomment-225549870
This said, I discovered that there is also a 32bits version of netsh in `SysWOW64` folder, and when using this one, Poedit works almost like a charm (live suggestions are Ok, collaboration also, the only problem is the 'Prferences > Accounts' which is doing "Updating user information" without ending.

To answer your questions:

output of `netsh winhttp show proxy` is

    Current WinHTTP proxy settings:
    Proxy Server(s) :  proxyar.ar.ray.group:8080
    Bypass List     :  *.ray.group;*.argroup;10.*;<local>

These are working well with Poedit last week version, but not with the new version.

I tried your proposal for the proxy-server=socks... and the error messages are still the same than https://github.com/vslavik/poedit/issues/276#issuecomment-227078618

**Comment by vslavik** [comment] 2016-06-20 09:04
> Poedit works almost like a charm

I.e. my proxy setting code in the new build is badly broken and your proxy is a HTTP one :(

> the only problem is the 'Prferences > Accounts' which is doing "Updating user information" without ending.

That seems to be unrelated to proxies, let’s create a new issue for it (I still can’t reproduce, unfortunately).

**Comment by tomolimo** [comment] 2016-06-20 09:05
and this user https://github.com/vslavik/poedit/issues/276#issuecomment-225630358 has the same problem

**Comment by vslavik** [comment] 2016-06-22 12:20
Could you try this executable? https://jumpshare.com/v/MTF71ibfQUKu6sR8EnA1 (preferably w/o proxy configured in `netsh`)

Note that it contains some logging messages, it would be useful to know both whether it works now and what the content of those messages is. Thanks!

**Comment by tomolimo** [comment] 2016-06-22 12:32
Hello,
I made a test with the new application, and I got this:

1. I removed proxy settings from netsh
1. I started poedit.exe
![image](https://cloud.githubusercontent.com/assets/7569958/16266530/a7c79a14-3885-11e6-9f64-c454726934b2.png)
1. And collaborate on translation project show this:
![image](https://cloud.githubusercontent.com/assets/7569958/16266559/d2ab6c1a-3885-11e6-814e-9698e469753e.png)
1. After a select of the project, I got this:
![image](https://cloud.githubusercontent.com/assets/7569958/16266591/ec3b186a-3885-11e6-8537-bad3508e6514.png)
1. But for preferences, I still got this:
![image](https://cloud.githubusercontent.com/assets/7569958/16266615/05b2d62a-3886-11e6-95fc-12dd6f54fca7.png)

So to sum-up: the new version is ok, apart the preferences

Thank you very much
regards,
Tomolimo

**Comment by vslavik** [comment] 2016-06-22 12:33
Thank you! Looks like Poedit got hit by this C++ REST SDK bug, then: https://github.com/Microsoft/cpprestsdk/issues/57

**Closed** 2016-06-22 15:12 UTC

**Comment by vslavik** [comment] 2019-02-12 15:43
I am making some changes to proxy handling that improve it, but I am not 100% certain about the handling of the edge case discussed in this bug. If you guys are still using Poedit behind a proxy and felt like it, trying this (stable) beta of upcoming 2.2.2 version would be appreciated: https://jumpshare.com/v/Jo1YyKH9VD4VIfqWMKDd
