### ISSUE TITLE
Can't modify catalog sources path, OS X 10.11.2

### ISSUE THREAD

**Issue by Saeven** [vslavik/poedit#229] opened 2015-12-15 20:31 UTC
First I see the catalog pref panel:
http://imgur.com/ObrtY62

Issues:
* Clicking on the little rightward arrow does nothing.
* Clicking on a file/folder in the path shows a file finder that has no "Open" or "Select" button, see http://imgur.com/HFfUOTq

**Comment by vslavik** [comment] 2015-12-15 20:44
Please see http://www.chiark.greenend.org.uk/~sgtatham/bugs.html and try to describe the problem better, because it’s not clear from the above why you think you can’t modify the paths list — no part of the description indicates any attempts to make any modifications to begin with.

So far you only demonstrated that you have a broken file that has hardcoded paths that you manually typed in as absolute paths (hence the missing icons in the path bar — that much I can deduce even though you didn’t even include the file). That Finder would be refusing to open such non-existent places should, frankly, to be expected, but I don’t think even that part is accurate:

Clicking on the items in the list *doesn’t do anything* — there’s no code to do anything. It certainly doesn’t open Finder (which is what your screenshot shows and not the file *panel* with buttons). It very much looks like everything works as it should and as is common in other apps: the link icon *does* do something: open Finder in the location (which is nonexistent, so it goes to the root). And for some reason, you’re ignoring the appearance of the Finder window and attributing it to some random clicking afterwards that in actuality did nothing. 

If that’s incorrect and if you still believe adding or removing paths (using the standard +/- buttons used by every other app on OS X) is somehow broken, please describe *how*, exactly, and how to reproduce it.

**Comment by vslavik** [comment] 2016-01-21 16:06
Closing due to lack of information.

**Closed by vslavik** 2016-01-21 16:06 UTC
