### ISSUE TITLE
Failed to load image from file "/org/gtk/libgtk/icons/16x16/actions/text-x-generic.png"

### ISSUE THREAD

**Issue by rolodoom** [vslavik/poedit#789] opened 2023-03-15 16:03 UTC
I'm getting this error when open Poedit in Manjaro Plasma, but not really sure where to look or if need a dependency.

![Screenshot_20230315_102543](https://user-images.githubusercontent.com/61945227/225368413-fc35cb29-7d85-4941-8c22-f9f8fbdae878.png)

```
can't open file '/org/gtk/libgtk/icons/16x16/actions/text-x-generic.png' (error 2: No such file or directory)
Failed to load image from file "/org/gtk/libgtk/icons/16x16/actions/text-x-generic.png".
can't open file '/org/gtk/libgtk/icons/16x16/actions/text-x-generic.png' (error 2: No such file or directory)
Failed to load image from file "/org/gtk/libgtk/icons/16x16/actions/text-x-generic.png".
```

**OS:** Majaro Plasma kernel 6.1.12-1-MANJARO
**Poedit:** version 3.2.2 from Community Repository

Hope maybe it's a missing dependency. But not a clue.

**Comment by vslavik** [comment] 2023-03-15 17:27
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1019704

Looks like wxGTK issue to me.

**Comment by cpontvieux-systra** [comment] 2023-04-06 14:35
Can poedit embed the icon?

**Comment by c72578** [comment] 2023-05-12 07:08
> Can poedit embed the icon?

The look of `text-x-generic.png` depends on the selected theme.

**Comment by Beryesa** [comment] 2023-06-06 17:10
Can replicate with the flatpak but that's not supported, so just noting for future searchers
Copying text-x-generic.png from runtime's Adwaita to local hicolor fixes the issue
here's a one-liner: 
```flatpak run --command=sh net.poedit.Poedit -c "mkdir -p $HOME/.var/app/net.poedit.Poedit/data/icons/hicolor/16x16/mimetypes/ && cp /usr/share/icons/Adwaita/16x16/mimetypes/text-x-generic.png $HOME/.var/app/net.poedit.Poedit/data/icons/hicolor/16x16/mimetypes/"```
Many themes back up to hicolor but not necessarily Adwaita, breeze happens to be one of them.

**Comment by Vistaus** [comment] 2023-08-15 11:09
I experience this issue as well. In the linked bug report, it doesn't look like they believe it's a wxGTK issue.

**Comment by vslavik** [comment] 2023-08-15 13:05
Please refrain from posting "me too" comments here that don't add any new substantial information. Thanks.

**Comment by Vistaus** [comment] 2023-08-15 13:07
I didn't just post a “me too” comment - I also added that in the bug report they don't believe it's a wxGTK issue. That's relevant information.

**Comment by vslavik** [comment] 2023-08-15 13:36
@Vistaus The latest comment in the linked issue predates this issue and does not, in fact, say what you claim it does. On the contrary, it specifically narrows it down to wxGTK not handling SVG icons correctly. Posting misinformation wastes even more maintainer time than "me too" 🤷‍♂️

**Comment by Vistaus** [comment] 2023-08-15 13:41
> @Vistaus The latest comment in the linked issue predates this issue and does not, in fact, say what you claim it does. On the contrary, it specifically narrows it down to wxGTK not handling SVG icons correctly. Posting misinformation wastes even more maintainer time than "me too" man_shrugging

What I see is “I cannot reproduce this - neither on Xfce, nor on Gnome.” by someone from the bug team.

Then the first poster updated it with a workaround, but that workaround does not work for me. So either way, there is an issue somewhere and Poedit is the only app where I am seeing this issue. So either it's a rare bug in wxWidgets (although the person from the bug team doesn't seem to think so) or it's an issue in Poedit (but the error is too generic to fully confirm that).

**Comment by Vistaus** [comment] 2023-08-15 14:02
Either way, I reported it upstream now, so let's wait for their answer: https://github.com/wxWidgets/wxWidgets/issues/23775

**Comment by vslavik** [comment] 2023-09-30 16:50
This will *probably* be mitigated by 8b564aac — as in, the underlying problem will still be there, but won't result in user-visible errors; rather, the files will have incorrect or no file icons in the sidebar.

**Comment by vslavik** [comment] 2023-12-08 18:44
The mitigation seems to be working. I'm closing this because the real problem can only be fixed in wxGTK, not Poedit.

**Closed by vslavik** 2023-12-08 18:44 UTC
Labels: Linux
