### ISSUE TITLE
The state of the "Need work" toggle button is not reported through accessibility APIs

### ISSUE THREAD

**Issue by CyrilleB79** [vslavik/poedit#721] opened 2021-10-31 14:41 UTC
The pressed/not pressed state of the "Need work" toggle button is not reported through accessibility APIs.
The tests have been done with NVDA and Narrator.

This issue is initially described in #693 (https://github.com/vslavik/poedit/issues/693#issuecomment-844973094, https://github.com/vslavik/poedit/issues/693#issuecomment-945850254https://github.com/vslavik/poedit/issues/693#issuecomment-945869171)
But since there were two issues described in #693, I open this ticket to talk about the state of the push button that needs to be reported.

To fix this issue, there may be (at least) two paths:
- have the "pressed" state reported via accessibility APIs
- change the "Need work" control to another type supported better by accessibility APIs, e.g. checkbox instead of push-button.

**Comment by vslavik** [comment] 2021-10-31 17:16
Duplicate of #693.

**Closed by vslavik** 2021-10-31 17:16 UTC
