### ISSUE TITLE
When quitting Poedit with a modified file, the Save button doesn’t work

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#169] opened 2015-05-01 09:00 UTC
To reproduce:

1. Open Poedit with any translation
2. Change something in the translation, but don’t save
3. Close the window. A confirmation dialog is shown.
4. Click Save.

The dialog is hidden, and nothing happens. Neither is the file saved, nor is the main window closed.

**Comment by vslavik** [comment] 2015-05-01 09:15
Presumably also 1.8beta1 @ Windows (please always include essential info like that)?

In that case, confirmed, but not reproducible with 1.7.6 here.

**Comment by vslavik** [comment] 2015-05-01 11:07
Regression caused by fdd83235, will be fixed in 1.8beta2 (later today).

**Closed** 2015-05-01 12:50 UTC
