### ISSUE TITLE
Descenders don't show up

### ISSUE THREAD

**Issue by milotype** [vslavik/poedit#593] opened 2019-07-30 16:25 UTC
The descenders of Bold text don't show up.
Font-settings of the app have not been changed. 
MacOSX 10.11.6. Poedit 2.2.3 (5738)
(see attached file)

![GUI correction](https://user-images.githubusercontent.com/43657314/62147069-06aa4880-b2f7-11e9-9421-04df548274fd.png)

**Comment by vslavik** [comment] 2019-09-18 15:58
Thanks for reporting! Will be fixed in 2.2.4.

**Comment by milotype** [comment] 2019-10-10 19:21
I know it's not essential, but I want to inform you … The descenders in the green button still don't show. And the green button itself doesn't look "complete" (upper corners are rounded, lower ones are actually missing).
MacOSX 10.11.6. Poedit 2.2.4 (5785)

![descenders2](https://user-images.githubusercontent.com/43657314/66599223-00f89b00-eba3-11e9-93ec-bbde0cd6dfd3.png)

**Comment by vslavik** [comment] 2019-10-11 09:24
Thanks :( I addressed the systematic sizing issue that could be causing it. Part of the trouble is that I couldn't reproduce it in your language at all, but could in Czech partially. 

This may be specific to you rather old OS version. From the screenshot I gather this is not a retina display, right? 

Reopening, I'll try to figure it out. In the meantime, you know what workaround to use to not have to look at that misrendered green box ;)

**Comment by vslavik** [comment] 2019-10-13 14:21
The explanation turns out to be very simple: I accidentally forgot to merge Poedit Pro's 36d6256 counterpart. Will be *fully* fixed in 2.2.5.

🤦‍♂️

**Closed by vslavik** 2019-10-13 14:21 UTC
Labels: macOS
