### ISSUE TITLE
Make options dialog resizeable

### ISSUE THREAD

**Issue by libreajans** [vslavik/poedit#613] opened 2019-12-27 19:12 UTC
Hi @vslavik 

Could you make option dialog resizeable? I think, because of my font, I can't see the last font option. 

![2019-12-27 21-31-55 ekran görüntüsü](https://user-images.githubusercontent.com/6218679/71529409-929bbd00-28f5-11ea-9e59-990b12b20e0f.png)

**Comment by fitojb** [comment] 2019-12-27 23:04
The solution for a spacing bug is not to make the dialog manually resizable; IMO that is not a desirable feature in modal dialogs…

**Comment by vslavik** [comment] 2019-12-30 13:15
Duplicate of #390.

Help with investigating or fixing it welcome. The behavior is a mystery and I am not able to reproduce it even with *much* more detailed information than what is present here.

**Closed by vslavik** 2019-12-30 13:15 UTC
Labels: Linux
