### ISSUE TITLE
TMX import error

### ISSUE THREAD

**Issue by Carmina16** [vslavik/poedit#828] opened 2024-01-13 19:52 UTC
PoEdit 3.4 is unable to import TMX files exported by some earlier version. It complains about the TMX files containing no translations.

If I manually add the field `srclang="en"` to the TMX `header`, it seems to import the file.

**Comment by vslavik** [comment] 2024-01-14 08:56
Please do provide steps to reproduce, including any involved files. You only present your hypothesis about what's happening, but not present any way to verify it.

**Comment by vslavik** [comment] 2024-07-04 09:47
Closing as invalid due to OP going incommunicado.

**Closed by vslavik** 2024-07-04 09:47 UTC
