### ISSUE TITLE
Find window freeze

### ISSUE THREAD

**Issue by soiamsoNG** [vslavik/poedit#346] opened 2017-03-07 05:39 UTC
Fedora 25 Workstation X86_64
Poedit 1.8.12
Locale zh_CN.UTF-8

Can not input in the field in the find window.
Can not move the window, if move the program will crash.

In the same time, the Preference window work correctly.

**Comment by vslavik** [comment] 2017-03-07 08:53
Please [read this](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) and do a better job of describing the issue and *steps to reproduce*. Please also consult your OS documentation on how to capture crashes and provide debugger output. 

Seeing how this is a very new version, I assume (even though you don't mention this sort-of-important detail) that you compiled from sources. The most likely explanation, then, is that you miscompiled wxGTK. There's pretty much no other way (well, except a broken WM) that *moving a window* would result in a crash in Poedit, which doesn't care about window *movement* at all and doesn't react to it.

**Comment by soiamsoNG** [comment] 2017-03-07 09:54
Sorry I can not dig deeper, I can give out more detail & step

I am not compile from the source, but install by the package manager (dnf)
Poedit version 1.8.12-1.fc25

**step 1.** open the Poedit
**step 2.** open a .po file
**step 3.** ctrl + f call out the find window
the button on the window function correctly
the text input field on the window can not be input
if use mouse to move the find window will crash with SIGSEGV
below is the report
[https://retrace.fedoraproject.org/faf/reports/1587407/](https://retrace.fedoraproject.org/faf/reports/1587407/)

**step 4.** step 1 -> step 2 -> and go to use the Preference window  and it function correctly.

I check the wxGTK3.x86_64 is version 3.0.2-32.fc25

**Comment by vslavik** [comment] 2017-03-07 10:02
That backtrace is showing, clearly, a crash happening in Wayland client library, not Poedit. This is a Wayland or GTK+ bug in Fedora, not a Poedit one. 

Also duplicate of Fedora's own bug: https://bugzilla.redhat.com/show_bug.cgi?id=1428348

**Closed by vslavik** 2017-03-07 10:02 UTC

**Comment by c72578** [comment] 2017-03-07 10:15
See also this Fedora bug report:
https://bugzilla.redhat.com/show_bug.cgi?id=1408674
Current workaround for translators using Poedit under Fedora 25:
Login using either "GNOME on Xorg" or "GNOME Classic".
