### ISSUE TITLE
"Updating user information..." won't stop loading

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#278] opened 2016-06-20 18:20 UTC
Hello,

Following issue #276, when opening Preferences > Accounts tab, logging in to Crowdin and "authorizing app", Poedit will display "Updating user information..." and it won't stop.
Tried disconnecting, reconnecting multiple times- nothing. Have no proxy. Disabled my COMODO Firewall for a while and tried again, still loading forever. This happens from when I first installed Poedit.
My UAC is disabled on my Windows. Tried running Poedit.exe (from Program Files) as admin anyway, did the whole login process again but this after clicking Authorize App time I got this error:
```
21:03:15: Failed to create connection to server 'Poedit' on topic 'cmdline': a client's attempt to establish a conversation has failed.
21:03:15: Failed to create connection to server 'Poedit' on topic 'cmdline': a client's attempt to establish a conversation has failed.
21:03:16: Failed to create connection to server 'Poedit' on topic 'cmdline': a client's attempt to establish a conversation has failed.
21:03:16: Failed to communicate with Poedit process.
```
If that's helping somehow, after clicking "Authorize App" I'm getting a blank page with only "[]" at the top.
Tried also setting Google Chrome as default browser, did again the process but the same result: stuck on "Updating user information..." (on Google Chrome the aforementioned blank page with "[]" does not appear)

Don't have any more info for troubleshooting so.. tell me what else you need.

Thanks.

**Comment by ItielMaN** [comment] 2016-06-29 13:12
It's getting lonely here..

**Comment by vslavik** [comment] 2016-07-01 17:20
> It's getting lonely here..

Please don’t engage in this sort of bugging. You filed the report, all the information is there, I’ll get to it. Bugging is not going to speed anything up.

> Disabled my COMODO Firewall 

Off-topic public service announcement: [COMODO are mean assholes](https://letsencrypt.org/2016/06/23/defending-our-brand.html).

> did the whole login process again but this after clicking Authorize App time I got this error:
> 21:03:15: Failed to create connection to server 'Poedit' on topic 'cmdline': a client's attempt to establish a conversation has failed.

That must be because you were running two Poedit instances, or trying to run it in two sessions, and it has no relation to this issue. Other than confirming that URL launching probably works…

> If that's helping somehow, after clicking "Authorize App" I'm getting a blank page with only "[]" at the top.

That does seem like some problem with some problem with your browser. What I’m missing here is more information about that (very relevant) part: *what* browser it was, in what version, on what Windows version. Also whether it asked for confirmation to open a `poedit://` URL and if you allowed it (I’m guessing you did) and when was this `[]` shown: before or after the `poedit://` question?

**Comment by ItielMaN** [comment] 2016-07-02 18:25
> Please don’t engage in this sort of bugging

Sorry, no bugging intended, it's just my way of gently nudging :)
> That must be because you were running two Poedit instances, or trying to run it in two sessions, and it has no relation to this issue. Other than confirming that URL launching probably works…

Hmm, I think you're kinda right, when confirming the Authorize App request, another instance of Poedit is being opened, even though there is one already opened. So yeah, not related.
> What I’m missing here is more information about that (very relevant) part: what browser it was, in what version, on what Windows version

Mozilla Firefox 47.0.1 Hebrew locale
Windows 10 Pro x86 Hebrew locale
> Also whether it asked for confirmation to open a poedit:// URL and if you allowed it (I’m guessing you did) and when was this [] shown: before or after the poedit:// question?

Here's exactly what's happening:
1. I open Poedit from the start menu, normally
2. File > Preferences > Accounts tab > Connect > Firefox is being opened with the Authorize App thing
3. I click the "Authorize App" button
4. I see a new window saying that "this link should be opened with an external program", and Poedit is listed & already selected. I click OK.
**Note:** Right after clicking the "Authorize App" button in Crowdin's page, the page at the main browser is being re-painted with only the [] thingy while I see the new window saying "this link should be opened with an external program" etc. The page's URL remains the same, but it's title is changed to the URL (instead of the previous "Authorize App - Crowdin").
5. The focus is automatically changed from Firefox to the already opened Poedit instance, and I see "Updating user information...". And the rest is history. It's stuck like that forever.

Hope that's detailed enough.
I can try to gif this whole operation if needed.
But again, I don't think the browser is at fault since the same is happening with Google Chrome (latest version), but without the [] showing up.

Thanks.

**Comment by ItielMaN** [comment] 2016-07-12 17:29
I just tried setting Internet Explorer as the default browser and whole thing is happening again (no [] in IE though).

If it helps, the full URL path of one of the poedit:// requests is:
poedit://auth/crowdin/#access_token=fd072b3096ff009d84cfc5d690c95637dd17f1b3&expires_in=31536000&token_type=Bearer

Here's all what I can think of that can make my system unusual:
1. The Windows is hebrew build.
2. The User Account name (in C:\Users) has only non-english characters (hebrew in my case).
3. Window's date and time is configured to Jerusalem UTC+02:00, the date format is dd/mm/yyyy, and the time & time zone are configured automatically.
4. The internet is connected directly from the PC to the router using a cable, no specific DNS/IP/Subnet Mask etc settings are applied. Using IPv4.
5. UAC is disabled.
6. VirtualBox is installed, so under Network Connections there's also an active "VirtualBox Host-Only Network". Disabling it doesn't change much.
7. COMODO Internet Security installed (as I've said before). Disabling ALL of it's components doesn't change anything,
8. TeamViewer is also installed and opened in the system tray.

-------------------------------------------------------------------

Okay, scratch that.
I now know how to reproduce, but you'll possibly need to create another Crowdin account for that.
And here's why:
My account was one without Name (in Crowdin's user settings, General Information tab).
Once I entered some text there, updated it and tried to sign in with Poedit, I saw the account information right away.
But! Removing the Name and updating it still makes Poedit connect and show the information (but with nameless Name).
That's why I think that only way to reproduce is to create a new account WITHOUT ENTERING A NAME IN THE REGISTRATION PROCESS.
I should note that at the same time of updating the Name, I also updated the user's time zone, though I don't think it matters for this issue.

I can't believe I managed to find the root cause! :)

**Comment by vslavik** [comment] 2016-07-12 17:35
> If it helps, the full URL path of one of the poedit:// requests is:

(FYI, I censored it out, because it’s sensitive info, akin to your password.)

> I can't believe I managed to find the root cause! :)

It’s clear for some time now that as far as bug reporters go, you’re close to the “miraculous” end of the spectrum, so I’m not that surprised :-)

This does indeed sound plausible, thank you *so* much for coming with the idea!

**Comment by vslavik** [comment] 2016-07-13 13:22
Fixed now, thanks again for figuring out the cause! I suspect I never would myself...

**Closed by vslavik** 2016-07-13 13:22 UTC

**Comment by ItielMaN** [comment] 2016-07-13 16:02
> Fixed now

I take it you've managed to log in to a newly created Crowdin's user that has no name through Poedit with your new build?
(Also, did you think what to add to Poedit's Accounts tab on Settings where no name is set on the Crowdin's user? Currently it will simply be blank. I thought about something like "Name is not available. Why?" where the hovering the "why" shows a tooltip explaining why, and how to fix)

> thanks again for figuring out the cause! I suspect I never would myself...

Nah, I simply thought that if it's not a networking/software issue (since a. I disabled everything I could think of that may conflict with Poedit, b. System OS's language shouldn't be a problem since it happened also to @tomolimo, who has english OS, c. All other internet-based softwares are working properly and d. It happened in all browsers), it must be something beyond that. That thing would be the Crowdin account itself.. :)

Thanks for the fix!

**Comment by vslavik** [comment] 2016-07-13 17:12
> I take it you've managed to log in to a newly created Crowdin's user that has no name through Poedit with your new build?

Yes (and it simply uses the login name, see the linked commit — it doesn’t really matter and isn’t worth spending any more time on).
