### ISSUE TITLE
Impossible to use a Norwegian Nynorsk spellchecker

### ISSUE THREAD

**Issue by jeblad** [vslavik/poedit#750] opened 2022-04-30 11:04 UTC
I tried to add several different spellcheckers with Norwegian Nynorsk dictionaries, but it does not seem like poedit can find any one of them. It is quite common to have problems with the identifier for Norwegian Nynorsk. The language id is "nn", not "no-nn" (as variant) or "nn-no" (with country) or anything similar.

This is on Ubuntu 21.10, Gnome 40.4.0, poedit 3.0.1.

Last translation into Norwegian Nynorsk was [Gnome Secrets](https://l10n.gnome.org/vertimus/secrets/master/po/nn/). Another one is [Gnome Authenticator](https://l10n.gnome.org/vertimus/authenticator/master/po/nn/), but currently it seems like there is something wrong with the last repo. Probably a known bug that bites.

Any pointers to what might be wrong would be greatly appreciated!

**Comment by vslavik** [comment] 2022-04-30 11:12
Please read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (which GitHub asked you to do when you created this issue), follow the instructions therein and provide the missing detailed information — this is nowhere near sufficient to reproduce. Thanks!

> It is quite common to have problems with the identifier for Norwegian Nynorsk.

Unless *you* misidentified the language in your file, this is unfounded speculation that isn't useful; more details, which are missing, would be. 

> poedit 3.0.1

From where?

> Last translation into Norwegian Nynorsk was [Gnome Secrets](https://l10n.gnome.org/vertimus/secrets/master/po/nn/).

Please do attach actual files and provide actual precise steps to reproduce, including precise description of *how to tell* something is wrong. Not everybody is Norwegian speaker.

**Comment by jeblad** [comment] 2022-05-26 09:41
The precise steps is to install poedit, and then try to translate _any_ project into Norwegian Nynorsk. I tried all available spellcheckers for Ubuntu, none of them seems to work with poedit. On this particular machine poedit comes from flathub, but I have also used deb-packages from the Ubuntu repos.

I get a message like “Stavekontrollen er deaktivert fordi ordlisten for norsk nynorsk ikke er installert.” (Awful translation!) It should be source string like “The spell checker is disabled because the Norwegian Nynorsk dictionary is not installed.”

![Screenshot of poedit v3.0.1, from 2022-05-26 11-13-47, showing Norsk Nynorsk translation of po-file for Gnome Secrets.](https://user-images.githubusercontent.com/4649804/170457777-bb956209-ec25-4078-8267-fd7e711fd0f5.png)

If I try to write Nynorsk, then I get squiggly lines underneath, but on correct Norwegian Nynorsk words. From what's lacks squiggly lines it seems like poedit is using a Norwegian Bokmål spell checker and it is not disabled as the message claims.

Spellcheckers for Swedish, Danish, and Norwegian Bokmål works, but not Norwegian Nynorsk.

**Comment by jeblad** [comment] 2022-05-26 10:48
Seems like there is an issue with alternate dictionaries in apps installed from flatpaks due to application isolation. I'm not sure how this works in this particular case, but in effect you can only use the system dictionary.

If I change the system language to Norwegian Nynorsk it works as expected (weird message though), but if I use Norwegian Bokmål as system language then spellchecking Norwegian Nynorsk fails.

Removing the flatpak and installing a deb package from the repo made it work as expected. For the moment I have Norwegian Bokmål as system language, and a po-file for Norwegian Nynorsk open for editing and it works as expected. It underlines misspelled Norwegian Nynorsk words.

I have probably translated Swedish and Danish while using poedit from a deb-package, and being mistaken that I did this while using poedit from flatpack.

The weird message from poedit could be because it could not set or change the dictionary, but then the same message should appear for Norwegian Bokmål too and not just for Norwegian Nynorsk. Not sure why.

I should add that it seems like this system (Ubuntu 22.04 LTS) tries to use hunspell as spell checker, but it only has a dictionary for Norwegian Bokmål (hunspell-no). I'm pretty sure that one is Bokmål, it is quite common to use "no" even if that is the macro language. The hunspell spell checker can use myspell dictionaries, and there are separate ones for Bokmål (myspell-nb) and Nynorsk (myspell-nn).

**Comment by vslavik** [comment] 2022-05-27 15:52
> The precise steps is to install poedit, and then try to translate any project into Norwegian Nynorsk.

You're being willfully obtuse by acting as if *this* vague hand-waving was precise. That document that you didn't read explains the need for clarity very well. And things like  "correct Norwegian Nynorsk words" (not everybody speaks your language!) are vague and unhelpful.

> (Awful translation!)

Instead of complaining and demeaning other people's contributions, please do contribute improvements in the spirit of Open Source.

> Seems like there is an issue with alternate dictionaries in apps installed from flatpaks due to application isolation.

We do not provide any flatpak packages.

Closing because this isn't a Poedit issue, but a 3rd party packaging one.

**Closed by vslavik** 2022-05-27 15:52 UTC
Labels: Linux

**Comment by jeblad** [comment] 2022-06-07 09:56
Thanks for your thoughtful reply.
I guess I just switch to another program.
