### ISSUE TITLE
Core dump when using IBus input 

### ISSUE THREAD

**Issue by MLSci** [vslavik/poedit#840] opened 2024-04-26 07:59 UTC
STR:
1. Open a `.po` file
2. Place cursor in the `Translation` box
3. Switch IBus input method to another language
4. As soon as the first word is typed in the `Translation` box, the app crashes

Output from `journalctl -xe` -

Operating System:

**Comment by vslavik** [comment] 2024-04-26 08:10
> STR:

Please provide more precise steps, including basic version information (Poedit, and the source of it), versions of dependencies (wxGTK, GTK+). Steps 3 and 4 are a bit too vague and could be done in different ways.

The stacktrace you provide is without debug information and so not very usable - the only thing that can be observed from it is that Poedit itself doesn't show up in it (which doesn't mean that Poedit code didn't cause it, though).

Can you please get the debug symbols (your distro has instructions on doing it) and run it under debugger to produce a symbolicated backtrace? TIA.

**Comment by MLSci** [comment] 2024-04-27 07:02
Poedit: 3.4.2, installed from Flatpak.

GTK+: 4.14.3

Step 3: click on the tray icon of IBus to toggle between two langauges

Step 4: the mechanism of typing Chinese is 
1. type the letters
2. a candidate box will show up on the screen. User selects the correct candidate character by using number key
3. the candidate character shows up in the field
In my case, the app crashes at the 3rd one - as soon as the candidate I selected shows up in the field, the app crashes

I'll get more debug info when I get a chance, since I'm still learning. For now we can close it

**Comment by MLSci** [comment] 2024-04-27 07:03
Poedit: 3.4.2, installed from Flatpak.

GTK+: 4.14.3

Step 3: click on the tray icon of IBus to toggle between two langauges

Step 4: the mechanism of typing Chinese is

1. type the letters
2. a candidate box will show up on the screen. User selects the correct candidate character by using number key
3. the candidate character shows up in the field

In my case, the app crashes at the 3rd one - as soon as the candidate I selected shows up in the field, the app crashes

I'll get more debug info when I get a chance, since I'm still learning. For now we can close it

**Comment by vslavik** [comment] 2024-04-27 07:14
> Step 3: click on the tray icon of IBus to toggle between two langauges

Do you have reason to believe it actually is, as you say, toggling between *any* two languages? Did you try it with many languages? Or is it rather that you only tried with two languages which you use - but which you didn't spell out? 

> Step 4: the mechanism of typing Chinese is

So you imply that this is about Chinese - probably not "e.g. Chinese", as you wrote initially, but specifically Chinese. But there are at least two, if not more, different input methods for it, and you don't specify.

> type the letters

This may come as a surprise to you, but not everybody in the world speaks Chinese, or has any idea how it is typed. Which is, again, why I asked for specific detailed reproduction instructions. Please do provide them. Please do not assume that I am Chinese (I am not) or that I speak Chinese (I don't) or know how to type it (I don't). Walk me through the keystrokes to reproduce.

> For now we can close it

When you file a bug, you're asking other people to spend time on your issue. It's very rude and disrespectful to then just close it. By doing so you're just 100% wasting others' time and are saying that while you ask others to spend time helping *you*, you can't be bothered to spend a little time helping *them* with the issue.

I'm reopening. Please provide a description of how to reproduce it that a non-Chinese person can follow so that I can try to reproduce it. Thanks.

**Comment by MLSci** [comment] 2024-04-27 08:13
I take it back. It's the users' fault for using this app. Pointing fingers is not constructive - it only shows bigotry and bias

**Comment by vslavik** [comment] 2024-04-27 08:15
Wow. Just wow. Your kind is why people quit open source.

**Comment by vslavik** [comment] 2024-04-27 08:19
Closing because the OP vandalized the description and removed crucial information 🤷‍♂️

**Closed by vslavik** 2024-04-27 08:19 UTC
Labels: Linux
