### ISSUE TITLE
linking issue with lucene++ 3.0.8

### ISSUE THREAD

**Issue by rosorio** [vslavik/poedit#684] opened 2021-02-17 15:48 UTC
Compiling poedit with latest lucene++ release fails reporting ld erors

```
ld: error: undefined symbol: Lucene::StringUtils::toUnicode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
>>> referenced by transmem.cpp
>>>               tm/transmem.o:(TranslationMemoryImpl::Search(Language const&, Language const&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&))
```

The breakage occurs after commit [9fe7860](https://github.com/luceneplusplus/LucenePlusPlus/commit/9fe7860465c765be8ebaaeef8c4ec5fe2252a65d)
and affects poedit 1.8.4 and 2.4.2

Poedit compilation log : [poedit-1.8.4_33.txt](https://github.com/vslavik/poedit/files/5996682/poedit-1.8.4_33.txt)

**Comment by vslavik** [comment] 2021-02-17 16:15
Sounds like a problem with your build environment or with LucenePlusPlus to me. 

If you believe otherwise, submit a PR with a fix. Unlike me, you do have an environment (details of which you don't provide) where you can reproduce it. If you're savvy enough to build Poedit from sources, you're savvy enough to investigate and fix.

P.S. Spamming both involved projects with no investigation and no attempt to identify the responsible project is not cool.

**Comment by rosorio** [comment] 2021-02-17 16:51
Sorry if you feel spammed, I'm Just reporting an issue and asking for some help.

Regarding the context, couple of weeks ago lucene++ was upgrade in FreeBSD ports (from 3.0.7 to 3.0.8) 
and since  poedit doesn't build anymore.
Reverting the upgrade back to 3.0.7 solves the problem.

I built poedit using lucene++ modified versions from 3.0.7 to 3.0.8, integrating one by one the commits 
and, as I said, I found the one who breaks.

Now I need to figure out if the issue is caused by an update un lucene++ API or build options introduced by error
in lucene++ or  not properly used by poedit  yet.

Maybe finding a fix can be beneficial for everyone.

Regards.

**Comment by vslavik** [comment] 2021-02-17 16:55
> Sorry if you feel spammed

I don't "feel" spammed, I'm telling you that filing the identical issue in both projects, as you did (that's not a "feeling", that's observable fact), is frowned upon.

> Maybe finding a fix can be beneficial for everyone.

It would be. Which is why I asked you to be of benefit to the project you use and investigate and contribute a fix. Probably best start by using LucenePlusPlus' *master* (which has evidently-build-related fixes since the last release) and looking into *why* you get linker errors.

**Comment by vslavik** [comment] 2021-02-20 10:32
Per LucenePlusPlus duplicate, evidently a build issue  →  closing.

**Closed by vslavik** 2021-02-20 10:32 UTC

**Comment by rosorio** [comment] 2021-04-08 21:54
The .pc file provided by lucene++ package has invalid library path "-L", which causes linkage errors on poedit with FreeBSD.
Sorry for the noise.
