### ISSUE TITLE
Heavy saving in poedit 2.3.1

### ISSUE THREAD

**Issue by dasj19** [vslavik/poedit#635] opened 2020-05-31 05:38 UTC
Hello, I would like to report heavy saving in the latest version.

Whenever I do Ctrl+S I am unable to continue editing for about a minute. I can click menu buttons like Help but I am unable to get the editor to edit text.

Using the save button gives me back the opportunity to edit.. but an extra mouse movement and clicking wastes precious time when translating.

**Comment by vslavik** [comment] 2020-05-31 06:20
Please read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (which GitHub asked you to do when you created this issue), follow the instructions therein and provide the missing detailed information. Thanks!

**Comment by vslavik** [comment] 2020-06-19 08:05
Closing as non-reproducible due to OP going incommunicado.

**Closed by vslavik** 2020-06-19 08:05 UTC
