### ISSUE TITLE
Crash when dropping PO file to Poedit

### ISSUE THREAD

**Issue by rffontenelle** [vslavik/poedit#409] opened 2017-07-06 14:21 UTC
Drag-and-dropping a PO file to poedit's window with crash with the following command line output:

> (poedit:11070): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
> 
> (poedit:11070): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
> 
> (poedit:11070): Gtk-WARNING **: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkToggleButton)
> 
> (poedit:11070): Gtk-WARNING **: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkToggleButton)
> 
> (poedit:11070): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
> poedit: cairo-arc.c:189: _cairo_arc_in_direction: Assertion `angle_max >= angle_min' failed.
> 

**Distro:** Arch Linux 64-bit
**Packages:**
* [poedit](https://www.archlinux.org/packages/community/x86_64/poedit/) 2.0.2
* [wxgtk3](https://www.archlinux.org/packages/extra/x86_64/wxgtk3/) (GTK+3 implementation of wxWidget)

If you need more info, please let me know.

**Comment by vslavik** [comment] 2017-07-06 14:31
Duplicate of #396.

> If you need more info, please let me know.

See the other bug. Help with diagnosing this wxGTK/GTK+ bug is sorely needed.

**Closed by vslavik** 2017-07-06 14:31 UTC
Labels: Linux
