### ISSUE TITLE
Need update "POT-Creation-Date"

### ISSUE THREAD

**Issue by urkokul** [vslavik/poedit#417] opened 2017-07-23 10:05 UTC
Need update "POT-Creation-Date" along with the "PO-Revision-Date" updating while saving a file in Poedit.
Thanks

**Comment by vslavik** [comment] 2017-07-23 10:49
Poedit does, of course, update `POT-Creation-Date` when appropriate. I'm guessing it's not appropriate in your case, but because you didn't bother to actually *describe* the situation, I'm just guessing. Therefore, closing.

But if you believe there is an actual issue, please read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html and provide complete, clear and detailed reproduction instructions and I'll reopen it.

**Closed by vslavik** 2017-07-23 10:49 UTC

**Comment by urkokul** [comment] 2017-07-23 10:59
Thanks

2017-07-23 13:49 GMT+03:00 Václav Slavík <notifications@github.com>:
