### ISSUE TITLE
"Update from Sources" working in 1.7.7, but disabled in 1.8.7 (OSX)

### ISSUE THREAD

**Issue by lukearmstrong** [vslavik/poedit#272] opened 2016-05-09 08:06 UTC
I've installed POEdit from the downloads page (not the App Store) and for some reason when I update to 1.8.7 "Update from Sources" is disabled. If I then re-install 1.7.7 the functionality comes back.

**Comment by vslavik** [comment] 2016-05-09 08:09
You don’t have properly configured source paths, making updating from sources impossible.

If you believe otherwise, amend the issue with sufficient information *and all the files* needed to reproduce (something that you should have done in the first place, because how do you expect me to know what you did wrong when you don’t tell me what you’re doing with your files at all?).

**Comment by lukearmstrong** [comment] 2016-05-09 08:11
I understand your frustration, but to give you the complete folder structure I would essentially have to upload the entire wordpress site, which my employers and their client would probably frown up. I will try to reproduce the issue with a Hello World app.

**Comment by vslavik** [comment] 2016-05-09 15:00
You could have attached just the PO file and the relevant bits, or send it privately. But there’s nothing I can do with this little information ant no mind-reading ability…  So yes, please do provide something reproducible.

**Comment by vslavik** [comment] 2016-07-12 16:05
Closing as “works for me” due to non-responsiveness of the reporter.

**Closed by vslavik** 2016-07-12 16:05 UTC
