### ISSUE TITLE
Slow network will hang online TM autocompletion, and finally hang the whole program.

### ISSUE THREAD

**Issue by Arthur2e5** [vslavik/poedit#200] opened 2015-08-26 22:01 UTC
It seems that TM operations will hang the POedit program for a while. This is OK for local TM since it won't take long, but for online TM fetching it's quite easy to notice.

**Comment by Arthur2e5** [comment] 2015-08-26 22:05
It appears that POedit is requesting those translation one by one, making the speed even slower. Is something like a bulk API available from MyMemory?

**Comment by vslavik** [comment] 2015-08-27 11:47
> It seems that TM operations will hang the Poedit program for a while. 

No, sorry, this is just not true *at all*. Please don't try to (wrongly) diagnose the cause of whatever it is that you're seeing and instead *describe* the problem in some reasonable amount of detail. Please describe what you do, *how* you do it, exactly and step by step, including providing any necessary files to reproduce it and information about your Poedit version, and of course the observed behavior.

It's also not clear what "slow network" means here — low bandwidth, high latency, unreliability, some combination of those or all of the above? Nor for that matter what "hang the whole program" does.

I know for a fact that pressing e.g. Ctrl+1 (my best guess as to what could you mean by "autocompletion") couldn't possible "hang" the app, so you probably meant something else. The problem is, you didn't explicitly say *what*...

> It appears that POedit is requesting those translation one by one

Given that you are translating things one by one, you of course need the *suggestions* (not final "translations"!) one by one as well…

**Comment by Arthur2e5** [comment] 2015-08-27 23:51
I am talking about Catalog -> FIll missing translations from TM.

**Comment by Arthur2e5** [comment] 2015-08-27 23:54
Slow Network means a network that takes ~1.5s to see each translation filled with the online TM.

**Comment by vslavik** [comment] 2015-08-30 17:43
> Slow Network means a network that takes ~1.5s to see each translation filled with the online TM.

That's the *observed effect* the network is having on Poedit (although I'm not quite sure how could you have measure that in *Fill Missing…* where individual entries handling isn't directly visible). I was hoping, since you filed an issue in the devel bug tracker, to get a *technical characteristics* of said network. That would be very useful in reproducing the problem and improving the code; "it's slow" is unfortunately a bit less so.

> I am talking about Catalog -> Fill missing translations from TM.

Ah, I see, that wasn't apparent to me. Yes, that code is problematic, please notice how it is marked as *experimental* in the UI. Indeed, the lack of bulk API (or any support for such use) is part of that. The suggestions aren't really meant for any bulk use, this functionality is intended strictly for the "offline commuter" use case.

**Closed by vslavik** 2015-08-30 17:43 UTC
