### ISSUE TITLE
POEdit not responds after I paste "„" sign

### ISSUE THREAD

**Issue by ViBE-HU** [vslavik/poedit#728] opened 2021-12-04 13:47 UTC
I'm using Ubuntu 20.04 and in Hungarian language quoting starts with the "„" sign. When I insert it the program become useless.

I'm using the 2.3-1build3 deb package.

More details: https://en.wikipedia.org/wiki/Quotation_mark#Hungarian

**Comment by vslavik** [comment] 2021-12-04 13:48
Please read [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (which GitHub asked you to do when you created this issue), follow the instructions therein and provide the missing detailed information. Thanks!

**Comment by vslavik** [comment] 2023-06-15 18:04
Closing due to OP going incommunicado.

**Closed by vslavik** 2023-06-15 18:04 UTC

**Comment by ViBE-HU** [comment] 2023-06-16 07:13
What else information should I provide?

**Comment by vslavik** [comment] 2023-06-16 07:24
You need to *read* things before replying... You got the instructions above more than a year ago.

**Comment by ViBE-HU** [comment] 2023-06-16 08:02
Sure. Now I remember why I forgot to reply first. So you have a program for a specified task: translation. The only thing I ever did with POEdit is translate. That means I input translated texts into the one and only _translated text_ field and that was the process too when I pasted/typed `„` sign.

I don't want to argue but you definitely know what is the purpose of POEdit. And if we talking about years... it took more than ~1.5 years for you to not try to reproduce a very clear thing and close the report while reproducing it takes about 10 secs if you have any kind of script files. And you still cannot answer what exactly holds you back from trying. The bug is still present in 3.3.1. But forget it. Keep overthinking. It helps a lot.

Peace.

**Comment by vslavik** [comment] 2023-06-16 08:15
This may come as news to you, but other people really can't read your mind. It is not possible to reproduce a bug that you are incapable of describing even remotely coherently. To this day, I have *no idea* what the heck you were talking about. That one half-formed sentence of the original description is nowhere near as  descriptive as you seem to think — included vague hand-waving about "program become useless" instead of actual, you know, *description of what happens*.

The article I asked you to read on the same day — which you ignored then and ignore now — does explain these things very well and teaches you how to file non-crappy bug reports.
