### ISSUE TITLE
How did I translate this word?

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#463] opened 2018-03-16 15:26 UTC
As far as I know, Poedit doesn't support glossaries. One question I frequently have is "How did I translate this single word previously?". It would be cool if I could just mark the word, right-click on it and get the answer:

![image](https://user-images.githubusercontent.com/3233724/37528240-700e4996-2934-11e8-89f9-5c7f19f694fd.png)

The menu item "Show previous translations" would then open another window that filters all the translations where this word appears in the source text.

Now that I think of it, such a window would be useful in general. It should be in addition to the editing window so that I can quickly search for translations without changing the current editing position in the file.

![image](https://user-images.githubusercontent.com/3233724/37529158-b1a70224-2936-11e8-8026-178ac2555d68.png)

**Comment by vslavik** [comment] 2018-03-16 15:29
Duplicate of (your own) #166.

**Closed by vslavik** 2018-03-16 15:29 UTC
Labels: Feature Request

**Comment by rillig** [comment] 2018-03-16 15:43
Damn, I knew it sounded familiar to me. :)
