### ISSUE TITLE
Ctrl-F opens find dialog in wrong scope

### ISSUE THREAD

**Issue by emesik** [vslavik/poedit#453] opened 2018-01-09 21:23 UTC
Pressing Ctrl-F opens find dialog within the context of the current message (a small text input field beside "Source text" label bar). Instead it should open the global search in a popup window. At least this is what the description of Edit/Find menu item suggests.

**Comment by vslavik** [comment] 2018-01-10 15:06
My psychic powers tell me this is a duplicate of #398.

If this is a wrong guess, please do provide basic information (as asked to in point 3 of the guide shown to you when creating a new issue), such as platform, versions of everything and more detailed steps to reproduce.

**Closed by vslavik** 2018-01-10 15:06 UTC
