### ISSUE TITLE
Poedit crashes with "assertion failed: (gtk_text_byte_begins_utf8_char (text))" during editing a translation with iBus input method

### ISSUE THREAD

**Issue by brlin-tw** [vslavik/poedit#513] opened 2018-09-04 05:47 UTC
Misc. output has been stripped, a copy of the full [console-output.log](https://github.com/vslavik/poedit/files/2347187/console-output.log) is available.

```
$ snap run poedit
**Gtk:ERROR:/build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtktextsegment.c:195:_gtk_char_segment_new: assertion failed: (gtk_text_byte_begins_utf8_char (text))
已經終止 (核心已傾印) -> Terminated (core dumped)
```

This is a self-built v2.1.1-oss-11-g7b902ba snap, with no modifications to the source tree.

**Comment by vslavik** [comment] 2018-09-04 10:16
This log doesn't contain anything useful, I'm afraid.

[Useful information](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) for this sort of bug is detailed reproduction steps — including what exactly to type, where, *how* (in the past such issues were content-specific); written in a way that a person who doesn't know what "iBus input method" is, how to get & enabled it or *how to type using it*, can comprehend and follow. 

In the context of snaps, it would be useful to know if it happens in normal builds too, but that's checkable on my end.

**Comment by Lin-Buo-Ren** [comment] 2018-09-04 12:03
You might be interested in this currently in-developing topic:  
[Collecting debug symbols - snapcraft - snapcraft.io](https://forum.snapcraft.io/t/collecting-debug-symbols/7017)

**Comment by vslavik** [comment] 2022-10-14 13:19
Not reported since then, closing as probably being an issue with snap runtime (which was since updated many times).

**Closed by vslavik** 2022-10-14 13:19 UTC
Labels: Linux
