### ISSUE TITLE
Unable to Athenticate poEdit with Crowdin behind firewall and proxy

### ISSUE THREAD

**Issue by AdyGould** [vslavik/poedit#217] opened 2015-10-08 10:13 UTC
I have been trying to authenticate poEdit behind a firewall and proxy configuration at work.
poEdit brings up the crowdin authorize page but clicking their button does not communicate with poedit to complete the round trip.

System: Windows 7
Browsers: IE8, Firefox 39, Chrome 45

**Comment by vslavik** [comment] 2015-10-08 10:22
Please provide enough information to reproduce — this isn't. What Poedit (notice the spelling, btw ;) version do you use, is it the latest? How did you install it — as admin, non-admin user? Can you describe what *happens* (rather than what does *not*)? When you click that Crowdin authorize button, the browser redirects to a custom `poedit://`URI to complete the auth. This *must* provoke some reaction from the browser, and probably a different one in different browsers, in the form of opening Poedit, a confirmation dialog or some sort of error.

If it really doesn't, the only other explanation I have right now, in absence of more info, is that your proxy is screwing with the page. Can you please check the following?

1. What is the link on the authorize button (right click, copy link)?
2. This page should be on SSL if I'm not mistaken — if you check the certificate, who's the issuer?

**Comment by vslavik** [comment] 2015-12-08 17:43
Closing because original reporter went incommunicado. There’s nothing I can do without more details.

Feel free to reopen if you encounter this *and* can answer the questions from the above comment.

**Closed by vslavik** 2015-12-08 17:43 UTC

**Comment by tomolimo** [comment] 2016-06-09 08:02
Hello,
I've got exactly the same problem, and here is the screen copy of the dialog box resulting of the 'authorize' button in crowdin:

![image](https://cloud.githubusercontent.com/assets/7569958/15922613/f3307a0a-2e28-11e6-8c03-f777d6da9e45.png)

What I know is that URL with protocols other than HTTP(s) are rejected by our corporate proxy.

Could it be possible to have an HTTPS:// instead of POEDIT://?

Thank you,
Regards,
Tomolimo

**Comment by vslavik** [comment] 2016-06-13 10:07
Further discussion, including how to fix your proxy configuration, continues in #276.

**Comment by vslavik** [comment] 2016-06-20 08:15
Can you please try this build: https://jumpshare.com/v/nDAdWSIYsQQ1jyLrJEGT (replace Poedit.exe in installed version with the one from the ZIP) and see if it correctly autodetects your proxy settings? If it doesn’t, could you show me (here or privately) your proxy settings in IE?

**Comment by tomolimo** [comment] 2016-06-20 08:17
Yes, this my last post: https://github.com/vslavik/poedit/issues/276#issuecomment-227076410

**Comment by vslavik** [comment] 2016-06-20 08:18
> Yes, this my last post: #276 (comment)

That wasn’t meant for you, but for **#217**…

**Comment by tomolimo** [comment] 2016-06-20 08:18
no problem :smile:
