### ISSUE TITLE
Close, Restore and Minimize buttons are trimmed on Windows 10

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#266] opened 2016-04-11 20:22 UTC
Hello,

In the new RTL fixes build, the Close, Restore and Minimize buttons seems to be trimmed a little. Well, it's more like all these icons moved down a little:
![c1](https://cloud.githubusercontent.com/assets/18016656/14441101/cf9fe780-003b-11e6-8d81-016f0219358a.png)
Image of the stable version (that's how it should look like):
![c2](https://cloud.githubusercontent.com/assets/18016656/14441127/fdcfa636-003b-11e6-9a00-0aaf19809806.png)

The same issue applies for the english version.

Thanks.

**Comment by vslavik** [comment] 2016-04-12 07:46
I believe this is unrelated to RTL and is caused by 83071864800e3792055573fa95375820238be71b, which was an attempt to remove that ugly 2px separator between menu and toolbar. And it breaks in your case because *your titlebar is smaller*. How did you accomplish that? 

If I’m right in my guess, then this replacement `Poedit.exe` won’t exhibit the bug: https://jumpshare.com/v/kBAHMmPJ03WD7a4RoxTB

**Comment by ItielMaN** [comment] 2016-04-12 10:08
> I believe this is unrelated to RTL and is caused by 8307186, which was an attempt to remove that ugly 2px separator between menu and toolbar

If you ask me, that separator is okay for me.. Unless it looks [darker in your machine](https://github.com/vslavik/poedit/issues/255#issuecomment-200903439).

> And it breaks in your case because your titlebar is smaller. How did you accomplish that?

I don't think I did much.
The 2 things I can think of that may change this appearance is the titlebar/taskbar color (does that matter?) and my screen's size (15 inch, 1024x768 resolution).
Also, it doesn't look like that titlebar is smaller. The 2 images I've shown were taken from the top left screen, and if you'll watch closely, it looks like the set of the icons are in a lower position than usual.

> If I’m right in my guess, then this replacement Poedit.exe won’t exhibit the bug

Yes sir, replacing the Poedit.exe fixes the issue.

**Comment by vslavik** [comment] 2016-04-12 17:00
Better: https://jumpshare.com/v/4uFmRglRURjDcatzFNRw ?

**Comment by ItielMaN** [comment] 2016-04-12 17:09
Nope, same issue as before (also for the menus bar).

**Comment by vslavik** [comment] 2016-04-12 17:13
There’s something positively crazy about your Windows 10 :( The screenshot above is *not* a normal Windows 10 titlebar look: not only is it smaller (than mine, not previous Poedit versions; this could be explained by customized titlebar font), but it also contains an icon that I have never seen before (next to the red button: normally, including in Hebrew Windows 10, this is a *single* rectangle, not two merged ones). What’s going on? Looks like some third party software installed, which could explain weird behavior…

**Comment by vslavik** [comment] 2016-04-12 17:15
>  this is a single rectangle, not two merged ones).

Let’s pretend I never wrote that, OK? :-( Note to self: that’s a maximized window, stupid.

**Comment by ItielMaN** [comment] 2016-04-12 17:33
> Let’s pretend I never wrote that, OK? :-( Note to self: that’s a maximized window, stupid.

Lol :D

> not only is it smaller (than mine, not previous Poedit versions; this could be explained by customized titlebar font
Not sure why you think that way.
According to [this guide](http://www.tenforums.com/tutorials/19150-title-bar-text-size-change-windows-10-a.html), mine is configured to 9. I didn't even know there was an option to change that until I google searched.
I didn't make any changes to the title bar except changing it's color (using Windows' built-in feature, no third party softwares involved).

**Comment by vslavik** [comment] 2016-04-12 17:43
> Not sure why you think that way.

Because it was the only explanation I had for why your titlebar is noticeably smaller than mine (or anywhere else). Turns out, it’s because *it is maximized*, which makes it smaller.

Could you try *un*maximizing Poedit, quitting it, and re-launching it? Are the two artifacts (titlebar smaller, menu text corrupted) still there when *not* maximized?

**Comment by ItielMaN** [comment] 2016-04-12 17:54
You mean in your latest Poedit.exe? If so than yes, the menu text corrupted issue is still there.
Regrading the titlebar issue, it wasn't there even before your latest patch in unmaximized state (though maximizing it back after your instructions doesn't change anything and the titlebar still seems smaller).
If you need to watch it online in my machine I can give you my TeamViewer details in PM.

**Comment by vslavik** [comment] 2016-04-12 18:07
> If you need to watch it online in my machine I can give you my TeamViewer details in PM.

I appreciate the offer, but that wouldn’t help me much. I believe you the artifacts are there, but I need to understand what difference between our setups is causing it, so that I can reproduce it myself and debug it; just seeing it wouldn’t really help. I suppose I should try a full Hebrew install of Windows 10 next, not just Poedit...

**Comment by ItielMaN** [comment] 2016-04-12 18:41
> so that I can reproduce it myself and debug it

...And you can't debug it on my machine?

> I suppose I should try a full Hebrew install of Windows 10 next, not just Poedit...

If still you want to try that out, note that my Windows 10 is an upgrade from hebrew-language-package-installed Windows 7 (english in origin, and that's why some of my OS is in english [device manager, regedit and some more I guess]).
Not sure if it matters though.

**Comment by ItielMaN** [comment] 2016-04-12 18:50
Besides, wouldn't it be better if you just backout the 2px change? Unless it really bothers syou :)

**Comment by vslavik** [comment] 2016-04-13 10:04
What is your Windows version (File Explorer → File → Help → About Windows)? Mine is build 10586.164 and is Windows 10 Pro (shown under the copyright line there).

**Comment by ItielMaN** [comment] 2016-04-13 10:19
Yours I guess is a bit outdated (there are Windows Updates from yesterday).
Mine is Windows 10 Pro build 10586.218.

**Comment by vslavik** [comment] 2016-04-13 15:17
So it isn’t Windows version, it isn’t Hebrew version, I don’t know what the difference is in your machine. I tested on two Win10 machines, with no artifacts at all. A graphics card difference could explain the artifacts, but not, I think, the titlebar cropping.

Does this do any better by a chance (I don’t think it will): https://jumpshare.com/v/PItFqki8JIGd4sEGL1OE ?

**Comment by ItielMaN** [comment] 2016-04-13 17:23
Nope, same issues with this version.
If that wasn't obvoius, no such issues occurs in other programs.
Using onboard graphics card of Asus [H110M-K D3](https://www.asus.com/Motherboards/H110M-K-D3/), Intel HD Graphics 530.
Drivers installed by Windows Update. Techincally I can try to toy with different versions of the display drivers but the fact still remains that this is happening only in this preview version after the 2px change (as you said).

**Comment by vslavik** [comment] 2016-04-13 18:13
> If that wasn't obvoius, no such issues occurs in other programs.

It was. That doesn’t mean it can’t be an issue with a specific graphics driver *triggered by* the unusual (but valid, AFAICT) thing Poedit does.

At the risk of annoying you further, could you have a look at https://jumpshare.com/v/eqDWYNsr80WTrsM8acrc ? It does *not* fix things and it *will* render badly broken. This is how it looks here:
![parallels picture](https://cloud.githubusercontent.com/assets/145881/14504156/d1b74abc-01b3-11e6-92b0-9d50f26d3e9e.png)
The point of the exercise is to understand how it shows for you. If you could post full screenshots of the Poedit window of the previous version and this one, both with the red X area on (as in your original screenshots here), that should hopefully help me.

The thing is, if I break things intentionally as I did in this build, I *can* see an off-by-1-pixel problem with the button (but not any menu distortion), so I think I may be on the right track. And I’d like to at the very least understand if I have to undo the 2px fix everywhere or just in RTL...

**Comment by ItielMaN** [comment] 2016-04-13 18:48
> That doesn’t mean it can’t be an issue with a specific graphics driver triggered by the unusual (but valid, AFAICT) thing Poedit does

Hmm. Right.

> At the risk of annoying you further

No my friend, you can ask me whatever you like :)

Not full-screened Poedit, with your new build:
![1](https://cloud.githubusercontent.com/assets/18016656/14504745/be4a2a02-01be-11e6-88fa-f5a231ced205.png)

Full-screened Poedit, with your new build:
![2](https://cloud.githubusercontent.com/assets/18016656/14504767/da494170-01be-11e6-8851-9f5be1224209.png)

Full-screened Poedit, with your previous build:
![3](https://cloud.githubusercontent.com/assets/18016656/14504888/57b1c18c-01bf-11e6-86c1-24be5c7dccd1.png)

Not full-screened Poedit, with your previous build:
![4](https://cloud.githubusercontent.com/assets/18016656/14504918/7dac57e4-01bf-11e6-8f0b-14fc483ca9b5.png)

Need more pics?

> And I’d like to at the very least understand if I have to undo the 2px fix everywhere or just in RTL...

Why just in RTL? The same issue applies in the english version.

**Comment by ItielMaN** [comment] 2016-04-13 20:20
Somehow the Device Manager decided there is a new update for the display driver (although it didn't report of any new driver yesterday), installed, restarted Windows and still the same.
Just sayin'.

**Comment by vslavik** [comment] 2016-04-14 13:20
Am I right in observing that the artifacts are of the same kind as that in the toolbar in the broken build, but less frequently occurring? And that they don’t *always* show up (they are present in some screenshots, but not all) — and when they do, it’s in different positions?

**Comment by ItielMaN** [comment] 2016-04-14 15:50
> Am I right in observing that the artifacts are of the same kind as that in the toolbar in the broken build, but less frequently occurring?

Not right. They appear the same as the not-broken buid.

> And that they don’t always show up (they are present in some screenshots, but not all)

Also wrong.
They're *always* visible. Sometimes hovering/clicking the tabs makes them noticeably more corrupt, but they're apparent regardless.
And they *are* present in all the screenshots provided in this issue. Take a closer look.

> and when they do, it’s in different positions?

Umm, kinda? They do appear in different positions but not randomly (at least on my machine). Eventually after hovering/clicking the tabs a few times you'll see a pattern of the artifacts showing up.
Hope this makes sense to you.

**Comment by vslavik** [comment] 2016-04-14 15:54
> > but less frequently occurring?
> Not right

I meant spatially: your screenshot shows severe artifacts on the toolbar button (something I can see) and much less severe in extent in the menubar.

> They're always visible.

But your second screenshot doesn’t seem to have them… and the other have them in different places.

> Eventually after hovering/clicking the tabs a few times you'll see a pattern of the artifacts showing up.

Ah, so it’s dynamic, and the original screenshots don’t show how it *always* looks? 

In any case, I think you’re right that the only realistic solution, at least for now, will be to revert 8307186 :-(

**Comment by ItielMaN** [comment] 2016-04-14 16:07
> I meant spatially: your screenshot shows severe artifacts on the toolbar button (something I can see) and much less severe in extent in the menubar.

Ah, yes then.

> But your second screenshot doesn’t seem to have them… and the other have them in different places.

Take a closer look at the "File" tab, the first letter (the first from the right, fourth from the left. Remember, it's RTL for me :P).
It should look like "ק", but in the screenshot it's cut off in 2 parts of the letter.

> Ah, so it’s dynamic

Yes! dynamic. I was looking for that word.

> and the original screenshots don’t show how it always looks?

Indeed.

> I think you’re right that the only realistic solution, at least for now, will be to revert 8307186 :-(

:D

**Comment by ItielMaN** [comment] 2016-04-17 18:58
Unless you have different plans for the the 2px change, this issue can be marked as solved.
Working OK in the new build.

**Closed** 2016-04-22 17:54 UTC
