### ISSUE TITLE
Minimum height of Source and Translation fields should be smaller

### ISSUE THREAD

**Issue by rillig** [vslavik/poedit#348] opened 2017-03-09 04:19 UTC
Poedit 2.0beta3
Windows 10

The Source and Translation text fields are forced to have a minimum height of about 7 lines of text. When I'm translating, most messages are single-line, therefore I'd like the Source and the Translation text fields to be smaller in height, so that the texts are closer to each other on the screen.

![2017-03-09 05_11_29-gcc-7 1-b20170226 de po gcc 7 1-b20170226 geandert - poedit beta-version la](https://cloud.githubusercontent.com/assets/3233724/23735619/f84ac588-0486-11e7-96e2-21f5ff472485.png)

This becomes especially apparent when a message with plural translation is translated. Because then, the minimum height requirement applies to each of the English plural forms, which effectively hides the Translation text control:

![2017-03-09 05_16_40-gcc-7 1-b20170226 de po gcc 7 1-b20170226 geandert - poedit beta-version la](https://cloud.githubusercontent.com/assets/3233724/23735739/c5246d70-0487-11e7-9ddc-1febe29ad72c.png)

**Comment by vslavik** [comment] 2017-03-09 07:55
I'm confused  by this one too: you say the topic is too big minimal size, but then proceed to describe problems that have no relation to minimal size… and that I can't reproduce.

The actual minimal height is about 4 lines of text and this is to ensure that plural forms UI fits. If anything, your second screenshot would show the min size is *too small*, not too *big*. 

But the actual problem seems to be that the source and translation subareas are unbalanced: they are supposed to have the same size (with some fudge room for the plural case). 

Can you please give more detailed instructions on how to reproduce (incl. a file to do it with)?

**Comment by vslavik** [comment] 2017-03-09 07:56
Also, what's up with the rounded titlebars in your screenshots? That's not how Win10 normally looks, could it be related?

**Comment by rillig** [comment] 2017-03-09 20:45
Regarding the rounded corners in the screenshots: that's from Greenshot when I take a screenshot of a full window using <kbd>Alt+PrtScr</kbd>. When Greenshot is disabled and I use the native Windows screenshot feature, the corners are there. Therefore I think this is not related to the rest of this issue.

Let me try to reword what I really meant.

In the first screenshot, the Source text field has its full (minimum) size, while the Translation field is smaller. When I experienced that yesterday, that was the minimum size of the two text fields. I could not make them any smaller.

The weird thing is that I cannot reproduce it today. Maybe something changes after working with Poedit for some time. I have no idea though what this might be.

When I tried to reproduce this issue today with a freshly started Poedit, the minimum height of the Source and Translation text fields was about 3 to 4 lines, which matches your description and is perfect for me.

I'd say we close this issue until I can reproduce it reliably. Sorry for not having tried that from the beginning.

**Comment by vslavik** [comment] 2017-03-09 21:04
Let's keep it open for now - *something* is going on here that shouldn't, even if not 100% reproducibly.

**Comment by vslavik** [comment] 2017-07-21 14:21
I have a similar report that is affected by the font used — does disabling "Use custom text fields font" have any effect (it does in this other report, on macOS)?

**Comment by vslavik** [comment] 2017-07-21 15:19
I'm closing because I was able to reproduce the above mentioned issue on Windows too, so I am assuming this to be the same thing. 2.0.3 with the fix will be released very soon; if this problem still persists in it, please comment here and I'll reopen the bug.

**Closed** 2017-07-21 15:18 UTC
