### ISSUE TITLE
Feature: highlight diff/wdiff with previous msgid with copy

### ISSUE THREAD

**Issue by osamuaoki** [vslavik/poedit#506] opened 2018-08-11 21:57 UTC
Many msgid updates are typo changes (sometimes removal of extra space etc.) and additional text at the end.

Although having panel showing "Previous source text" is nice start as current program, I think we can do better.

The first step is to display "wdiff previous-msgid-string current-msgid-string" in the  "Previous source text" window location as "Change from previous source text".  Let's make it selectable from the "View" menu.

The second step is to make display of wdiff more user friendly by displaying its output with user friendly font usage.  I mean that the removal from previous msgid string as strike-through font and the new addition of the msgid string as underlined bold font.  (I mean "wdiff --terminal" equivalent display)

The third step is offering of a method to copy inserted text to the text copy buffer.  I think if underlined bold font string as mentioned above is pointed, it should offer it to be copied by right click.  This helps to copy complicated marker string inserted to be handled easily.

All these are are deterministic and highly useful feature for updating fuzzy gettext output.

If you don't want to contaminate source, call wdiff with 2 temporary file.  Then no GPL contamination issue.  Just check command availability to enable view option.

**Comment by vslavik** [comment] 2018-08-13 10:47
> we

I’m glad you see it that way, what a refreshing change! Please contribute a PR to that effect and I’ll be happy to merge it.

Until then, closing as duplicate of #230.

**Closed by vslavik** 2018-08-13 10:47 UTC
