### ISSUE TITLE
PoEdit doesn't take all color from the system themes

### ISSUE THREAD

**Issue by Getron** [vslavik/poedit#298] opened 2016-11-10 16:16 UTC
Hi

Please look at the image, the Poedit should better implement with system themes. The right bar is allway white, and the text color is hard to see.

I have tryed in my Manjaro 16.10 Arch Rolling Release couple of styles for GTK2, but, this white background on the right side is stay white, and this looks ugly on dark themes, and it is not readable the text on it.

And the lang editing text, it has white background, and the cursor is not visible, where is it.

Please check this and fix it.

Thanks

![auswahl_283](https://cloud.githubusercontent.com/assets/5913218/20184640/a723ddb8-a769-11e6-94ca-d0470373b933.png)

**Comment by vslavik** [comment] 2016-11-10 16:29
Is checking existing issues as a good Open Source citizen really that hard?

Closed as duplicate of #273.

**Comment by vslavik** [comment] 2016-11-10 16:29
> Please check this and fix it.

Please help me fix it by contributing a patch?

**Closed by vslavik** 2016-11-10 16:29 UTC

**Comment by Getron** [comment] 2016-11-10 16:49
@vslavik if i go to issues, i see just 23 issues there, no more. now, i see 24. Why i don't see the other issues? i have searched first if exist similar problem, but, my github doesn't show me, just 23 issues, and you sended me the 273...????

How i can contribute you with patch?

**Comment by vslavik** [comment] 2016-11-10 16:51
If you have no experience with GitHub, please don’t use this issue tracker, you’re just adding pointless noise. There’s a LINK to the issue above, for crying out loud, and the issues are NUMBERED in the list.
