### ISSUE TITLE
Assertion error when trying to set a font with non-ASCII name

### ISSUE THREAD

**Issue by MingcongBai** [vslavik/poedit#208] opened 2015-09-14 03:23 UTC
An assertion error will occur when a font with non-ASII name is chosen.

`./src/common/string.cpp(1186): assert "c < 0x80" failed in FromAscii(): Non-ASCII value passed to FromAscii().`

And with backtrace:

```
ASSERT INFO:
./src/common/string.cpp(1186): assert "c < 0x80" failed in FromAscii(): Non-ASCII value passed to FromAscii().

BACKTRACE:
[1] wxString::FromAscii(char const*, unsigned long)
[2] wxString::FromAscii(char const*)
[3] g_signal_emit_valist
[4] g_signal_emit
[5] g_closure_invoke
[6] g_signal_emit_valist
[7] g_signal_emit
[8] g_main_context_dispatch
[9] g_main_loop_run
[10] gtk_main
[11] wxGUIEventLoop::DoRun()
[12] wxEventLoopBase::Run()
[13] wxAppConsoleBase::MainLoop()
[14] wxEntry(int&, wchar_t**)
[15] __libc_start_main
```

The font I used is the Kaigen Gothics family, it is possible to obtain the font from here, https://github.com/akiratw/kaigen-gothic.

Just in case, here is the package versions:

```
aosc [ TP@master ] $ LC_ALL=C dpkg -l poedit wxgtk-3
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                 Version                 Architecture            Description
+++-====================================-=======================-=======================-=============================================================================
ii  poedit                               1.8.4                   amd64                   cross-platform gettext catalogs editor
ii  wxgtk-3                              3.0.2-2                 amd64                   GTK+ implementation of wxWidgets API for GUI
```

**Comment by vslavik** [comment] 2015-09-14 09:05
Thanks!

> ```
> BACKTRACE:
> [1] wxString::FromAscii(char const*, unsigned long)
> [2] wxString::FromAscii(char const*)
> [3] g_signal_emit_valist
> ```

As a rule of thumb, backtraces are almost always almost useless when done without debug information. In this case, [3] onwards is either wrong or or there's a to missing between [2] and [3]. Could you install the corresponding `poedit-dbg` and `wxgtk-3-dbg` (I think) packages and try to get the assert again?

(I should be able to reproduce it without it too thanks to your detailed description, but it would make it easier to pinpoint the cause.)

Also, is this build of wxGTK using GTK+2 or GTK+3?

**Comment by MingcongBai** [comment] 2015-09-14 14:42
> [3] onwards is either wrong or or there's a to missing between [2] and [3]. Could you install the corresponding poedit-dbg and wxgtk-3-dbg (I think) packages and try to get the assert again?

I am not using any of the Debian or RedHat, SUSE series so... no dbg package is available... You might want to reproduce it yourself.

> Also, is this build of wxGTK using GTK+2 or GTK+3?

It is a GTK+2 build.

**Comment by vslavik** [comment] 2015-09-14 14:50
> so... no dbg package is available... 

So you might want to do whatever it is that you need to do to get the debug symbols... You also might want to report such basic information as what distro you are using.

Right now the backtrace doesn't support the hypothesis that it is related to fonts with non-ASCII names or that it's even a Poedit bug: seems more likely to be a wxGTK one. Hence my interest in getting a valid backtrace from a system *where the assert actually is reproducible.*

**Comment by MingcongBai** [comment] 2015-09-14 14:52
I will need to have a rebuild later today.

在2015年09月14，上午 8:50，Václav Slavík 
<notifications@github.com> 写道：

**Comment by vslavik** [comment] 2015-09-21 13:13
Closing as irreproducible — submitter won't provide requested information and the reproduction instructions are too vague to be reproduced (too many different downloads on the linked page, a random sampling of which contains *no* fonts with "non-ASCII names" at all fonts work just fine in Poedit).

Please reopen if you can provide a useful backtrace or *precise* and accurate instructions to reproduce the assert.

**Closed by vslavik** 2015-09-21 13:13 UTC
