### ISSUE TITLE
GUI becomes unresponsive when validating a specific .po-file

### ISSUE THREAD

**Issue by sebras** [vslavik/poedit#452] opened 2017-12-19 00:49 UTC
When validating the strings of [this .po-file](https://github.com/vslavik/poedit/files/1569859/gimp-master-po-sv-23093.merged.po.gz) in Poedit 2.0.5 I end up in a situation where the GUI becomes entirely unresponsive. I tested the same file in Poedit 2.0.4 and the issue does not appear there.

By running git bisect and compiling Poedit (with debug enabled) I learned that it is commit da949dcf64b810176df4ff15c850357fb7f69cc2 that introduces the issue for me (the commit prior, 7cd6eac8943b4452a0304c976d82a4a4091d1cec does _not_ exhibit the problem).

To reproduce:
1. Run: poedit gimp-master-po-sv-23093.merged.po Then I see:
![poedit1](https://user-images.githubusercontent.com/700468/34134481-20db67d2-e45b-11e7-8180-a6b528525d0b.png)
2. Click on the Validate toolbar button. For a split second I see:
![poedit2](https://user-images.githubusercontent.com/700468/34134484-2389b4ca-e45b-11e7-8150-c6da9fe8a860.png)
3. Next I wait for the dialog box to pop up (note that the list of strings has changed back to those from step 1):
![poedit3](https://user-images.githubusercontent.com/700468/34134487-24262e04-e45b-11e7-81e8-f73d5822eed1.png)
4. if I drag another window over Poedit's window it fails to redraw the contents:
![poedit4](https://user-images.githubusercontent.com/700468/34134486-23fc0d86-e45b-11e7-8735-76029e8fccf7.png)
5. If I drag another window over both Poedit's window and its dialog box, it fails to redraw the contents, but successfully redraws the dialogbox:
![poedit5](https://user-images.githubusercontent.com/700468/34134485-23b13f04-e45b-11e7-96c2-d363c9062a9c.png)
6. Next I click on OK in the dialog box and the window contents fails to redraw and the GUI is entirely unresponsive:
![poedit6](https://user-images.githubusercontent.com/700468/34134483-2360c998-e45b-11e7-9856-b740fa1fec01.png)

I attempted to debug this further, this is what I found (hopefully it helps you nail it down quicker):

When trying to minimize the .po-file, it sometimes worked, and sometimes did not. I noticed that when it didn't work step 2 occurred, but when it worked step 2 never ocurred. I think it might be a timing issue on a sufficiently big .po-file that has both untranslated messages and warnings.

Just as a test I removed the [the call to Sort() in PoeditFrame::OnValidate](https://github.com/vslavik/poedit/commit/da949dcf64b810176df4ff15c850357fb7f69cc2#diff-52c8dd65648ccef63c74b9aa24e24da6R1725). When I did that of course the lines were not sorted, but crucially the issue did not appear. I noticed that `Sort()` ends up as a call to `PoeditListCtrl::Sort()` which creates a `SelectionPreserver`. As my next test I reinstated the call to `Sort()` in `PoeditFrame::OnValidate()` but removed the call to `list->SetCurrentItem(item)` from `~SelectionPreserve`. When I did this the issue also stopped to appear. Despite discovering this I don't understand where the issue comes from.

I'm happy to help with further testing if you have trouble reproducing this issue.

Ďakujem vám, že ste rozvíjali Poedit! :)

**Comment by vslavik** [comment] 2017-12-19 14:51
Thanks for the detailed investigation! Can you please provide missing basics such as your platform and its version (GTK+ 2.x.y or 3.x.y, wxGTK version; distro)?

> Ďakujem vám, že ste rozvíjali Poedit! :)

You're mistaken in your assumption...

**Comment by sebras** [comment] 2017-12-19 15:09
> Thanks for the detailed investigation!

As a developer myself I appreciate detailed and _clear_ bug reports. I try to provide other developers with the same.

> Can you please provide missing basics such as your platform
> and its version (GTK+ 2.x.y or 3.x.y, wxGTK version; distro)?

Ah, yes, I should have realized this myself (though it would have been good if Poedit's issue guidelines here on github reminded me about this, I assume you have to ask about this pretty frequently).

I'm using Debian/testing which means that I used Poedit 2.0.5-1 from Debian and my locally compiled Poedit is on commit 4dc421578f2bb24c24d2db5a896070f9c534dd8b. Both are using GTK+ 2.24.31-2 and wxGTK 3.0.3.1+dfsg2-0v5.

> You're mistaken in your assumption...

Agh, I mixed up the languages for a bit. What I should have written was _of course_: 
Děkuji za rozvíjení společnosti Poedit! :)

**Comment by vslavik** [comment] 2018-01-11 15:38
I can't reproduce with wx 3.0.3 and GTK+ 2.24.31 on Fedora :(

**Comment by vslavik** [comment] 2023-12-08 18:42
> I can't reproduce with wx 3.0.3 and GTK+ 2.24.31 on Fedora :(

...and because I can't reproduce it with more modern versions of wx and GTK+ either, I think it's safe to close this now.

**Closed by vslavik** 2023-12-08 18:42 UTC
Labels: Linux
