### ISSUE TITLE
Menus bar issue in the new build 

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#265] opened 2016-04-11 20:15 UTC
Hello,

In the new RTL fixes build I've noticed a new display bug, which causes the menus bar to look corrupted.
I'll let the images speak for themselves:
The menus bar in the stable build:
![m1](https://cloud.githubusercontent.com/assets/18016656/14440902/c9b9af78-003a-11e6-88c1-5ec29b0f3d42.png)
The menus bar in the new build:
![m2](https://cloud.githubusercontent.com/assets/18016656/14440949/08052898-003b-11e6-84d8-92647ddf49f3.png)
It looks as if there are distortions in the menus bar.

I see this regardless of UI language.
Using Windows 10 x86 hebrew locale.

Thanks.

**Comment by vslavik** [comment] 2016-04-11 20:22
> I'll let the images speak for themselves:

I’d much prefer if you could explain it in words. You show two images that clearly differ in multiple things (different text, different menu items' states, different background at the top *and* bottom) and it is unclear which of those you’re referring to (I didn’t notice anything out of ordinary when running it myself)…

**Comment by ItielMaN** [comment] 2016-04-11 20:28
None of the above.
The texts are different due to the first image having older translation.

Take a look at how the *letters* themselves look like (you don't need to know hebrew to see that).
See how it looks in english:
![m3](https://cloud.githubusercontent.com/assets/18016656/14441334/06e04df6-003d-11e6-8e60-842fad413b77.png)

**Comment by vslavik** [comment] 2016-04-12 07:47
Can’t reproduce this either. Could this be another manifestation of #266, i.e. does the fix there remove this breakage too?

**Comment by ItielMaN** [comment] 2016-04-12 10:08
Yes it does.

**Comment by vslavik** [comment] 2016-04-12 13:40
Closing as (non-obvious) duplicate of #266 then.

**Closed by vslavik** 2016-04-12 13:40 UTC

**Comment by ItielMaN** [comment] 2016-04-12 13:58
Well it was obvious for me, but didn't want to break the don't-post-several-issues-in-one-post law :)
