### ISSUE TITLE
Poedit doesn't work with wxGTK 3.2.0 (latest stable)

### ISSUE THREAD

**Issue by DarkRedman** [vslavik/poedit#764] opened 2022-07-22 20:41 UTC
I'm using `poedit 1:3.1` (weird version number) on Manjaro (Arch Linux based) after updating the packages and it doesn't work with the new `wxwidgets-gtk3` package while **Filezilla** and **Audacity** doesn't have any issue with the newer version.

When I start it I get a bunch of Error Window with assertion errors such as :

`
ASSERT INFO:
/usr/src/debug/wxWidgets-3.2.0/src/gtk/bitmap.cpp(970): assert ""IsOk()"" failed in GetWidth(): invalid bitmap

BACKTRACE:
[1] wxBitmap::GetWidth() const
[2] wxEntry(int&, wchar_t**)
[3] __libc_start_main
`

**Comment by vslavik** [comment] 2022-07-23 08:40
Duplicate of #758.

Please also do pay attention to [instructions](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) when filing bugs.

**Closed by vslavik** 2022-07-23 08:40 UTC
Labels: Linux
