### ISSUE TITLE
Unable to build poedit 3.5

### ISSUE THREAD

**Issue by willysr** [vslavik/poedit#855] opened 2024-09-01 02:06 UTC
I'm testing poedit 3.5 on Slackware 15.0 and it failed to build with the log can be found here
https://github.com/SlackBuildsOrg/slackbuilds/pull/7782
the spesific error part are this:
```
fileviewer.cpp:153:28: error: incomplete type ‘wxWebView’ used in nested name specifier
fileviewer.cpp:155:16: error: invalid conversion from ‘wxWebView*’ to ‘int’ [-fpermissive]
fileviewer.cpp:164:17: error: invalid conversion from ‘wxWebView*’ to ‘size_t’ {aka ‘long unsigned int’} [-fpermissive]
fileviewer.cpp:320:14: error: invalid use of incomplete type ‘class wxWebView’
fileviewer.cpp:349:18: error: invalid use of incomplete type ‘class wxWebView’
make[1]: *** [Makefile:748: fileviewer.o] Error 1
make: *** [Makefile:483: all-recursive] Error 1
```

Another issue:
The README says C++REST SDK is optional, but now it's considered mandatory in 3.5

**Comment by c72578** [comment] 2024-09-01 04:57
@willysr Concerning the `wxWebView` errors: Please check the removal of wxGTK3 for correctness:
https://github.com/SlackBuildsOrg/slackbuilds/pull/7782/commits/bc22d93883ef6137f181b2b3cc9398388fc2fd09

```diff
- REQUIRES="wxGTK3 LucenePlusPlus gtkspell3 webkit2gtk"
+ REQUIRES="wxWidgets LucenePlusPlus gtkspell3 webkit2gtk cpprestsdk"
```

**Comment by willysr** [comment] 2024-09-01 05:02
@c72578 i assume that's what the ChangeLog in poedit 
https://github.com/vslavik/poedit/commit/22a556cdd68a5f280cac426eefbc8b2edcdbff99

**Comment by willysr** [comment] 2024-09-01 05:02
This part: upgraded to wxWidgets 3.2

**Comment by c72578** [comment] 2024-09-01 05:19
What about `webkit2gtk4.1` instead of `webkit2gtk`?

**Comment by willysr** [comment] 2024-09-01 05:59
let me try that, will let you know the result in few hours since the CI is retesting all scripts in the repository now

**Comment by willysr** [comment] 2024-09-01 16:33
@c72578 unfortunately that didn't work either
https://github.com/SlackBuildsOrg/slackbuilds/pull/7782#issuecomment-2323416371

**Comment by vslavik** [comment] 2024-09-02 12:52
> fileviewer.cpp:153:28: error: incomplete type ‘wxWebView’ used in nested name specifier

If you search this issue tracker, you will see that the cause is that you have incomplete build of wxWidgets. Poedit requires a full one. Closing as wontfix, because there's nothing that can be done about this in Poedit — you have to fix your build system to build all wxWidgets sublibraries.

> Another issue:

Please limit one issue to *one* issue. It's basic hygiene. If the README says something is optional, anything differing from that warrants creating an issue (but please, with actual details, not just off-hand remark like this). Thanks!

**Closed by vslavik** 2024-09-02 12:52 UTC

**Comment by willysr** [comment] 2024-09-02 13:06
I think i know why it builds fine on my machine and failed to build on CI
i have webkit2gtk and webkit2gtk4.1 installed and wxWidget SlackBuild have autodetect feature but the default is that webkit2gtk is not listed as a dependency so it doesn't build the webkit feature in the CI. I will try building with webkit2gtk listed as dependency and see how it goes.

@vslavik : Perhaps a note in the README about wxWidgets needs to be compiled with webkit feature enabled and not just Unicode? That should clarify for packagers

**Comment by vslavik** [comment] 2024-09-02 13:11
> Perhaps a note in the README about wxWidgets needs to be compiled with webkit feature enabled and not just Unicode? That should clarify for packagers

It says wxWidgets is required, not some *subset* of it, so reasonable reading is *all of wx*, no?

Configure [does list](https://github.com/vslavik/poedit/blob/a88e6d9131962df44ddbbe75a336fbda6c1e4960/configure.ac#L51) the used libs, but since `wx-config` doesn't enforce that, I did add explicit sanity check before replying here, see a88e6d9131962df44ddbbe75a336fbda6c1e4960

**Comment by willysr** [comment] 2024-09-02 13:26
yes, that should do it

**Comment by willysr** [comment] 2024-09-02 13:47
it's now built properly
thanks for the hint @vslavik and @c72578 :)
https://github.com/SlackBuildsOrg/slackbuilds/pull/7782

**Comment by vslavik** [comment] 2024-09-02 14:37
> The README says C++REST SDK is optional, but now it's considered mandatory in 3.5

OK, found the bug: 1673c796
