### ISSUE TITLE
GTK+ assert when opening a PO file

### ISSUE THREAD

**Issue by png2378** [vslavik/poedit#396] opened 2017-05-16 17:14 UTC
If I run Poedit and then open some po-file, everything is fine. But if I try to open po-file directly (for example from desktop), Poedit crashes.

Terminal log:
```
[maxim@ProBook]$ poedit gnome-software.master.ru.po
Fontconfig error: "local.conf", line 2: no element found

(poedit:23250): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:23250): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:23250): Gtk-WARNING **: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkToggleButton)

(poedit:23250): Gtk-WARNING **: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkToggleButton)

(poedit:23250): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
poedit: cairo-arc.c:189: _cairo_arc_in_direction: Assertion `angle_max >= angle_min' failed.
Aborted (стек памяти сброшен на диск)
```

OS: Fedora 26
DE: Gnome 3.24
Version: Poedit 2.0.2

**Comment by vslavik** [comment] 2017-05-17 09:16
From a quick glance, looks like you got an assert in a library Poedit uses (GTK+ or wxGTK, versions of neither of which you provide), not in Poedit itself. You probably should file a bug with Fedora.

If you think otherwise, please follow [this advice](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) and also provide backtrace from the debugger (with debug symbols compiled in!).

**Comment by png2378** [comment] 2017-05-17 17:30
So, I left [feedback](https://bodhi.fedoraproject.org/updates/poedit-2.0.2-1.fc26#comment-609490) in Fedora's update gating system. I hope that my info will help (I don't know how I can provide backtrace).

**Comment by c72578** [comment] 2017-05-18 14:36
Attached you will find a backtrace
Some version info:
Poedit: commit d2084cf36d7f2b568d36b49f0877810a95877622
wxGTK3.x86_64 3.0.3-1.fc26
gtk+.x86_64 1:1.2.10-83.fc26
gtk3.x86_64 3.22.15-1.fc26

[gdb_poedit_backtrace.zip](https://github.com/vslavik/poedit/files/1011220/gdb_poedit_backtrace.zip)

**Comment by c72578** [comment] 2017-05-19 08:09
In the meantime I could do some further tests.
- The problem appeared with this commit: f98feb2e42fe438d453a33fdab142fe1b708f038
git checkout f98feb2e42fe438d453a33fdab142fe1b708f038
commit f98feb2e42fe438d453a33fdab142fe1b708f038 (HEAD)
Author: pepc <pcondal@apsic.com>
Date:   Sat Mar 25 17:27:53 2017 +0100

    Add --line command-line switch

Problem appeared

- Previous commit: 0f9dac7d4b8ead501166e846ff00a7c40a9f1e87
git checkout 0f9dac7d4b8ead501166e846ff00a7c40a9f1e87
commit 0f9dac7d4b8ead501166e846ff00a7c40a9f1e87 (HEAD)
Author: Václav Slavík <vaclav@slavik.io>
Date:   Wed May 10 18:36:32 2017 +0200
    Highlight 2+ spaces in the middle of string too

OK

**Comment by vslavik** [comment] 2017-05-19 10:07
Thanks! That's a useful clue that I wouldn't have suspected.

**Comment by vslavik** [comment] 2017-06-01 17:19
This seems to be largely coincidental with f98feb2, not directly caused by it. Not reproducible with wx trunk either, only 3.0.

**Comment by Martchus** [comment] 2017-07-05 17:10
Maybe it is coincidental, but the issue also occurs under Arch Linux and the patch/revert provided by @c72578 fixes it here, too.

**Comment by Martchus** [comment] 2017-07-05 17:40
I've just responded because you've been closing the issue and I wasn't sure how to interpret your last comment. So thanks for making it clear. And I agree that the commit should not be reverted.

**Comment by vslavik** [comment] 2017-07-05 17:42
Yeah, I see the ambiguity now :(

**Comment by vslavik** [comment] 2017-07-21 14:05
> (And sorry, I apparently closed this by accidentally clicking the other comment button. Didn't mean to. If it can be worked around in Poedit code, it should.)

@Martchus Actually, I was confused: as seen in the log above, commit 86e0677 fixed this 4 days before your comment. Closing again; please reopen/comment only if you tested with the latest master, not 2.0.2.

**Closed by vslavik** 2017-07-21 14:05 UTC
Labels: High, Linux
