### ISSUE TITLE
File references seem to reformat no matter what the settings are

### ISSUE THREAD

**Issue by limi** [vslavik/poedit#606] opened 2019-10-31 21:26 UTC
Our extracted .po(t) files list file references one per line, but I see that multiple references per line is also valid. 

When loading this into Poedit — making no changes, but just hitting Save — it seems to reformat all file references, meaning that even a single string change results in a large diff.

I did try both checking and unchecking "Preserve formatting of existing files", but it doesn't seem to apply to file references.

Here's a screenshot of the diff, I have also attached a minimal test case example that shows this behavior: Load it, save it, and look at the diff to see the below:

![image](https://user-images.githubusercontent.com/105389/67986448-44658880-fbe8-11e9-9a3d-0f51483471bc.png)

Is there any way to avoid this? 

If this is incorrect behavior based on gettext spec, I can also file an upstream bug with the extraction tool we use, but as far as I can see, both approaches seem valid, and a single file reference per line make diffs a lot cleaner, so we'd like to preserve that if we can.

Poedit version 2.2.4 (5785) on macOS Catalina 10.15.1.

Example file (had to rename it to .txt since GitHub issues doesn't allow .po file attachments): [index-example.txt](https://github.com/vslavik/poedit/files/3795844/index-example.txt)

**Comment by limi** [comment] 2019-10-31 21:28
(And yes, I did find issue #213 which seems to be a variant of this problem, but in that case was an unrelated bug with counting line widths?)

**Comment by vslavik** [comment] 2019-10-31 21:38
> Is there any way to avoid this?

Yes — use standard formatting as produced by GNU gettext tools and you won't have any problems.

This is a duplicate of #94. I consider this behavior good enough, but you are welcome to (try to) improve it and submit patches if your priorities are different.

**Closed by vslavik** 2019-10-31 21:38 UTC
