### ISSUE TITLE
Not all missing placeholders reported?

### ISSUE THREAD

**Issue by kkmuffme** [vslavik/poedit#848] opened 2024-06-17 12:09 UTC
3.4.4

original:

```
Welcome to %s portal
```

translated:

```
Willkommen bei % Portal
```

It should
a) report an error that it's missing the placeholder in the translation
b) generally report errors when a single % is used, as in PHP 8 this will lead to a notice https://3v4l.org/En0lQ and it would be great if this could be caught early

**Comment by vslavik** [comment] 2024-06-17 13:07
Please provide an actual reproduction case, i.e. all involved files + steps to perform with them.

**Comment by vslavik** [comment] 2024-06-20 07:05
Again, can you please actually provide an actual reproduction case, i.e. all involved files + steps to perform with them? Not some censored half-quoted files, and vague hand-waving about what you did, provide *actual files* to check your settings and outputs, and *detailed steps* you did.

**Comment by vslavik** [comment] 2024-07-04 09:46
As expected, Poedit does in fact show an error in this case. `xgettext` does correctly extract the string from the provided PHP snippet and flags it as`php-format`, and Poedit reports it:

<img width="987" alt="Screenshot 2024-07-04 at 11 45 11" src="https://github.com/vslavik/poedit/assets/145881/8b93a0a7-58d9-4729-8651-0e0a9c0ad1bb">

When developers ask you to be precise, it's not to harass you, it's because you really don't describe the circumstances fully and they can't do much without full information. Going incommunicado in response only wastes everybody's time in the end. 

Closing as not reproducible, absent non-vague reproduction instructions form the OP.

**Closed by vslavik** 2024-07-04 09:46 UTC
