### ISSUE TITLE
The "ID" section takes up a lot of space

### ISSUE THREAD

**Issue by eshagh79** [vslavik/poedit#714] opened 2021-09-06 14:51 UTC
Hi
When the "Show ID" option is enabled, the ID field takes up a lot of space, leaving no space for the "Translate" and "Text Source" sections.

Reproduction:
1. Open the poedit application with a po file (any file)
2. From the toolbar, click the "View" button, and select the "Show String ID" option.
3. Resize poedit (resize too much)
Note: The "ID" field is not displayed before resizing (raised in another issue)

Additional information:
I am using Ubuntu 21.04.
poedit version 3.0-6
My computer language is Persian (RTL direction), but these problems exist even when the program is opened in English. 

I tried both window system (wayland) and (X11) and the problem persisted.
![نماگرفت از 2021-09-06 18-06-29](https://user-images.githubusercontent.com/52137191/132234656-0245e21a-f94a-4a68-aadb-0fd40b41dae4.png)
![نماگرفت از 2021-09-06 18-14-12](https://user-images.githubusercontent.com/52137191/132234666-6f0286bc-f82c-46dd-baf1-78590bf35bb1.png)

**Comment by vslavik** [comment] 2021-09-06 14:57
Please try the version from https://poedit.net and verify whether it's an issue with Poedit or Ubuntu packaging ("3.0-6" is evidently an Ubuntu package version, even though you don't say so).

**Comment by eshagh79** [comment] 2021-09-07 05:16
Hi again.
I installed the latest version of poedit from snap. And I can still reproduce the problem.
latest / stable: 3.0 2021-06-07 (30) 100MB -

**Comment by eshagh79** [comment] 2021-09-07 05:19
Although in is not related to this problem, but I have improved some Persian translation in crowdin if you can add it to poedit

**Comment by vslavik** [comment] 2021-09-07 16:45
> Although in is not related to this problem,

If you find yourself writing that in an issue, stop and don't hit the Comment button.

**Comment by vslavik** [comment] 2022-04-03 08:59
Please don't close issues without explanation. It's rude after you asked us to spend time on it, and is counterproductive.

**Comment by super7ramp** [comment] 2022-04-24 21:04
I can reproduce the issue with the following environment:

- Poedit version: 3.0.1
- wxGTK version: 3.1.6
- GTK+ version: 3.24.33
- Operating system: openSUSE Tumbleweed (20220414)

I think the issue comes from the fact that, at least on wxGTK, last `wxDataViewColumn`:

- Can grow despite its width being fixed
- [`wxDataViewColumn::GetWidth`](https://github.com/wxWidgets/wxWidgets/blob/v3.1.6/src/gtk/dataview.cpp#L3504), returns the actual width (i.e. `gtk_tree_view_column_get_width`), not the fixed width (`gtk_tree_view_column_get_fixed_width`).

When columns are sized in [`PoeditListCtrl::SizeColumns`](https://github.com/vslavik/poedit/blob/v3.0.1-oss/src/edlistctrl.cpp#L743), the ID column width, which is supposed to be fixed, is subtracted from the available width to determine the width of the other columns. But since ID column actually grows with the available space and `m_colID->GetWidth()` returns the actual width, the available width for the other columns doesn't change, hence the observed behaviour.

I don't see how it can be fixed without memorizing the ID column fixed width and using it in `SizeColumns()` instead of the value returned by `wxDataViewColumn::GetWidth()`. Or maybe there's a way in wxWidgets to make another column automatically grows when window is widened?

**Comment by vslavik** [comment] 2022-05-08 16:17
Fixed by 5e3ba48

**Closed by vslavik** 2022-05-08 16:17 UTC
