### ISSUE TITLE
Set POT File and Update From That

### ISSUE THREAD

**Issue by ravage84** [vslavik/poedit#820] opened 2023-10-19 16:18 UTC
Context:
While it is possible to set source paths and update a PO file from them it is not possible to set the (relative) path of the POT file.
Thus, one does always need to select the POT file manually

![grafik](https://github.com/vslavik/poedit/assets/625761/0783fb8a-84a8-415d-babc-8d0d92038909)

![grafik](https://github.com/vslavik/poedit/assets/625761/3a89c7c5-8142-45bb-9eb5-0e3f69df71df)

![grafik](https://github.com/vslavik/poedit/assets/625761/16bc7cc0-a8bd-4014-b7e1-293567fea8d5)

Feature request:
It would be nice to set the POT file for a PO file once and update from that without needing to select the POT file every time.

Rationale:
The path of a POT file most likely never changes and is most likey always the same (relative) to the PO file.
Also, selecting the wrong POT file leads to mismagled PO files, which is annoying.

**Comment by vslavik** [comment] 2023-10-19 16:21
Duplicate of #79.

**Closed by vslavik** 2023-10-19 16:21 UTC
