### ISSUE TITLE
OsX Version 2.0 crashes when updating catalog

### ISSUE THREAD

**Issue by ValentinCreative** [vslavik/poedit#365] opened 2017-03-30 06:33 UTC
Hi ! 

I got the version 2.0 for Mac Os. 
And when I want to update sources from php and phtml files it keeps loading forever. 
I must force kill the app. 

I had to get back to version 1.8.12

Since it just get stuck at loading, I dont get any error message. 
Is there some logs somewhere to investigate ? 

Thanks

**Comment by vslavik** [comment] 2017-03-30 07:50
Please provide sufficient information to reproduce — i.e. the PO file in question, the source code used, and step-by-step instructions on what to do with them. [This](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) has some helpful tips on describing circumstances around bugs too.

Thanks!

**Comment by vslavik** [comment] 2017-04-10 17:10
Closing because OP went incommunicado.

**Closed by vslavik** 2017-04-10 17:10 UTC
Labels: macOS
