### ISSUE TITLE
Problems when copy-pasting

### ISSUE THREAD

**Issue by beamath2** [vslavik/poedit#522] opened 2018-10-05 19:41 UTC
## Information
Version: 2.1.1
System: Windows

## Summary

1. If you copy any string to the clipboard from inside Poedit, all "\r" escape sequence literals are removed and replaced with what I assume is the rich-text equivalent (when you paste it back into Poedit, it adds newlines). This does not happen with "\n".

2. If you paste a string copied from outside Poedit, it adds another escape character before any backslashes for "\r" and "\n" and "\\" (but not other escape sequences), for example if you paste "\r\n" you will get "\\\r\\\n" inside Poedit.

## Expected Result
Escape sequence literals remain untouched.

**Comment by vslavik** [comment] 2018-10-06 08:45
Please follow the [advise](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) you were asked to read when you created the issue and provide *fully* reproducible description, with complete reproduction steps using *specific* texts. I don't know what exactly you might mean by ""\r" escape sequence literals" or "rich-text equivalent" or from *what* you're pasting, which highly matters. 

> for example if you paste "\r\n" you will get "\r\n" inside Poedit.

As a demonstration of confusing nature of your description, please observe how the above doesn't make sense, with both quoted strings being identical.

> Expected Result: Escape sequence literals remain untouched.

As far as I know, that is the case.

I think you are confused by the difference between *visualization* of unprintable characters and actual content. Poedit copies and pastes, for obvious reasons, the *actual* text, not its pretty-printing.

**Comment by beamath2** [comment] 2018-10-09 13:58
>Please follow the advise you were asked to read when you created the issue and provide fully reproducible description, with complete reproduction steps using specific texts

Ok, here's two specific examples, both tested on Windows with Poedit 2.1.1 (build 5418).

First example:
1. Copy this string to the clipboard from outside Poedit: "This is a string.\r\n".
2. From inside Poedit, paste the string into the "Translation:" box.
3. You'll get: "This is a string.\\\r\\\n"
**Problem**: it adds a second "\\" to both "\r" and "\n".

Second example:
1. Open a .po file with Poedit that contains a string in it such as this: "This is a different string.\rThis is another line.\r\n".
2. Copy-paste the whole string from the "Source text:" box to the "Translation:" box in Poedit.
3. You'll get this:
```
This is a different string.\n
This is another line.\n
```
**Problems**:
- It changes the first "\r" into "\n"
- It pastes the string over two lines instead of one (but that seems to be how Poedit shows all lines that end with "\n", so maybe not a bug per se)
- It removes the second "\r"

I hope these are clear enough.

> > for example if you paste "\r\n" you will get "\r\n" inside Poedit.
> 
> As a demonstration of confusing nature of your description, please observe how the above doesn't make sense, with both quoted strings being identical.

Sorry about that, problem with Github editor. What was meant is that "\r\n" becomes "\\\r\\\n". See examples above.

> > Expected Result: Escape sequence literals remain untouched.
> 
> As far as I know, that is the case.
> 
> I think you are confused by the difference between _visualization_ of unprintable characters and actual content. Poedit copies and pastes, for obvious reasons, the _actual_ text, not its pretty-printing.

As shown by the examples, this isn't the case for "\r" at least.

**Comment by vslavik** [comment] 2018-10-09 14:35
Again: Poedit *correctly* sets the item to what you pasted to it. It is *rendered* with some highlighting and escapes to show the actual content that would otherwise be invisible.

Paste a text with newlines and you'll get a text with newlines in it — as shown when you actually *use* the translation.

This is not a bug. This is working as intended.

> Open a .po file with Poedit that contains a string in it such as this

I don't have such a file and you didn't attach one...

---

With regards to your ill-advised use of `\r` specifically: Any time you run any gettext tool on such PO files, they complain and warn you that you shouldn't be using `\r` at all. It's a good advice.

It's entirely possible that there's some normalization of line endings that under some circumstances erases CR characters when copying and pasting around, due to CRLF normalization. Such handling would be hidden deep in wx and/or win32 code and would be difficult to track down. You are welcome to try, debug it and submit a PR with fix.

I am however closing the bug as WONTFIX, because the majority of what you describe is intentional. The one possible fridge case that might not be is when you do something you really, really, *really* shouldn't be doing in the first place, and when you insist and copying & pasting text between different applications while preserving your non-standard line endings. That's rare enough that I I think manually fixing it up is fine — or in any case, far less work than changing the behavior.

But again: if you disagree and *you* are willing to put work into improving it, I'd be more than happy to merge your changes.

**Closed by vslavik** 2018-10-09 14:35 UTC

**Comment by beamath2** [comment] 2018-10-09 16:28
>Again: Poedit correctly sets the item to what you pasted to it. It is rendered with some highlighting and escapes to show the actual content that would otherwise be invisible.

It doesn't. Try the examples. The changes happen when you paste. When you save the .po file, it simply writes what's displayed on-screen to the file.

By the way, if you use the right-click menu's "Copy from source text" option, it works properly (the string is copied verbatim, without changing or removing the `\r`)

>I don't have such a file and you didn't attach one...

Here you go: https://pastebin.com/wbhw1rfL Paste that into a .txt file and change the extension to .po.

>With regards to your ill-advised use of \r specifically: Any time you run any gettext tool on such PO files, they complain and warn you that you shouldn't be using \r at all. It's a good advice.

How is that my problem as a translator? I wish I could magically fix all the bugs and the misused escape characters in all the world's software, but I can't. Best I can do is not make the software throw up by keeping the formatting as-is.

>when you insist and copying & pasting text between different applications while preserving your non-standard line endings.

Only one of the two examples refers to copy-pasting from outside Poedit. The other is Poedit to Poedit copy-paste. I think I've made that clear in my first reply.

Any text editor that works with plain text files should not do CRLF normalization or any other kind of string manipulations when copy-pasting. You seem to agree when you literally override wx and GTK's default handling of copy-pasting in `text_control.cpp`.

>But again: if you disagree and you are willing to put work into improving it, I'd be more than happy to merge your changes.

I don't disagree that it might be too hard of a bug (or _behavior_, if you don't want to call it a bug) to track down and fix considering there's not many use cases, but please don't say that `the majority of what you describe is intentional` when it's clearly not.

**Comment by vslavik** [comment] 2018-10-09 16:53
> It doesn't. Try the examples.

I very well couldn't when you didn't provide them before, could I?

> When you save the .po file, it simply writes what's displayed on-screen to the file.

Please learn up on the format of PO files. They use escaping. Which happens (not entirely surprisingly given the history) to be close to what Poedit uses for interpretation. Which is why I asked you to look at the content as shown in-application *using* the translation.

> How is that my problem as a translator? 

I would think this issue answers that well… 

> throw up by keeping the formatting as-is.

Edit *in* Poedit instead of pasting from elsewhere and you won't have this issue. 

> Only one of the two examples refers to copy-pasting from outside Poedit. The other is Poedit to Poedit copy-paste. I think I've made that clear in my first reply.

You didn't at all. You gave two examples: one for copying from outside, one for copying within Poedit. The only thing you complained about in the latter is `\r`.

> Any text editor that works with plain text files should not do CRLF normalization or any other kind of string manipulations when copy-pasting.

1. Absolutely not. The worst messes of f***ed-up text files are those with inconsistent line endings because some crappy text editor allowed pasting without normalization.
2. PO files are structured files. They have meaning, which Poedit presents. If you want to get down to the metal, *use* a real plain text editor to edit them — you seem like that would make you happier. 

> You seem to agree when you literally override wx and GTK's default handling of copy-pasting in text_control.cpp.

You might want to spend some time with the code and associated git lots before making uninformed statements like that. This code is there to avoid rich formatting from being wrongfully applied.

> but please don't say that the majority of what you describe is intentional when it's clearly not.

Thanks for the lecture on what *my* intentions "clearly" are, but well, you are mistaken about that. Copying and pasting as the text actually *is* (i.e. newlines are actually newlines in it, not `\n` markup, backslashes are backslashes and not `\\` markup) is very much intentional.

Destroying some non-standard newlines *only when copy & pasting around manually* is unfortunate and it would be better if it didn't happen, but there's a lot of things I can improve in Poedit for *correct* uses of gettext that I'm really not interested in spending much time on something that is an edge case, shows up only with poor gettext uses and requires copying & pasting to be a problem.

**Comment by vslavik** [comment] 2018-10-12 10:39
> As I said before, copy-pasting from outside adds an additional \ before \n. But it doesn't do it for other things that must be escaped in a PO string, like ". The \n behavior is not correct, 

Did you not consider that there may be reasons for that, such as `\` being the escape character for newlines, while `"` is not? Please try to responsibly think about all aspects of such things before dismissing them as "not correct" with such certainty... 

> But it doesn't do it for other things that must be escaped in a PO string

Escaping in a written-out PO file is a matter of *serialization*. It is only loosely related to the actual *content of the text*. All `"` characters must be escape in the serialization; that's not a reason to bother the user manually escaping them. Newlines and special characters like tabs matter a great deal in translations, but are normally invisible: they must be indicated to the translator *somehow*.

> (that's probably another edge case of how you handle rich text and highlighting in the text boxes)

No, that's you actually including the newline in the copied text… Arguably, Poedit could be *smarter* here (something you seem to be dead-set against otherwise) and filter it out if the source text doesn't contain it and vice versa.

> P.S. Okay, dunno why I didn't try this earlier, but when copy-pasting from Poedit to other programs it just copies the text box content to the clipboard instead of the plain text that's shown in the box, i.e. it doesn't keep the escape characters as plain text.

You got it backwards. It copies the actual, i.e. plain, text. What you see is graphical rendering of that.

> That's unintuitive to say the least.

Quite the opposite, actually: in the far past, exposed markup was causing endless problems, both when editing directly and when copying.

> If you want to use the text with any other program, it won't match what you need to put in the PO file.

It *will* match, exactly, the content of the translation and what you need to paste in Poedit. It will be what you want to paste into another CAT tool, should you be so inclined. It doesn't match the PO *serialization*, just like copying from a web page won't copy the *markup* underneath it. 

> And please don't respond to that with "just don't copy an example from Poedit". That's not the point.

No, it very much is. If you want to show the *translation*, then pasting from Poedit does that. If you want to show *how PO file format looks*, then it — of course — doesn't. For that, use a plain text editor or `cat` the file.

As I said before: if you prefer raw view of the serialized PO files, use vim; Poedit is not a tool for that.

This seems pointless. You don't want to listen to the explanation, you just want to argue about it. I don't owe you spending time doing that, so I'm now closing this issue for good to save us both some time; let's agree to disagree on the subject. If you think some aspects can be improved, by all means please submit a PR for consideration, but please try keeping users that don't care about PO format's internals in mind — they are the *vast* majority of translators.
