### ISSUE TITLE
Flip the 'reload' icon in the Update button

### ISSUE THREAD

**Issue by ItielMaN** [vslavik/poedit#434] opened 2017-09-23 20:45 UTC
Hi again,

https://material.io/guidelines/usability/bidirectionality.html#bidirectionality-rtl-mirroring-guidelines
See "when not to mirror" section.
As the idea of the Update button is to "move time forward", the reload icon should be clockwise. Right now it's counterclockwise.

Current icon:
![default](https://user-images.githubusercontent.com/18016656/30776948-907caef2-a0b8-11e7-8059-6bec422a3e64.png)

**Comment by vslavik** [comment] 2017-09-24 07:04
Closing as (sub-)duplicate of #435.

**Closed by vslavik** 2017-09-24 07:04 UTC

**Comment by vslavik** [comment] 2017-11-23 17:54
I was a bit too quick to close this, as this issue is not actually about RTL mirroring, as it appeared to you: the icon has the same counter-clockwise orientation in both RTL and LTR.

You do have a valid point that "move time forward" orientation of the arrow would be better, but I think it's such a minor thing that it's not worth redoing the icons for.
