### ISSUE TITLE
Poedit doesn't work with wxGTK 3.0.2 (latest stable)

### ISSUE THREAD

**Issue by mariobl** [vslavik/poedit#366] opened 2017-03-30 07:50 UTC
Today I wanted to update to v2.0, and when opening a po file from the file manager, I get the same error message as described above. Here's the backtrace, as copied from the error window:

ASSERT INFO:
./src/gtk/dataview.cpp(211): assert "gtk_tree_selection_get_select_function(m_selection) == func" failed in CheckCurrentSelectionFunc(): selection function has changed unexpectedly, review this code!

BACKTRACE:
[1] wxDataViewCtrl::DoSetCurrentItem(wxDataViewItem const&)
[2] wxEvtHandler::TryHereOnly(wxEvent&)
[3] wxEvtHandler::ProcessEventLocally(wxEvent&)
[4] wxEvtHandler::ProcessEvent(wxEvent&)
[5] wxEvtHandler::ProcessPendingEvents()
[6] wxAppConsoleBase::ProcessPendingEvents()
[7] wxApp::DoIdle()
[8] g_main_context_dispatch
[9] g_main_loop_run
[10] gtk_main
[11] wxGUIEventLoop::DoRun()
[12] wxEventLoopBase::Run()
[13] wxAppConsoleBase::MainLoop()
[14] wxEntry(int&, wchar_t**)
[15] __libc_start_main

The system is Fedora 25 with wxGTK3-3.0.2. By the way, I can open Poedit from the application menu without problems. But after opening a po file, the same error will be issued.

**Comment by vslavik** [comment] 2017-03-30 07:52
Thanks. Now if you could *not* ignore the rest of the things I requested, i.e. proper reproduction steps (file and how *exactly* you "opened the PO file") *and enabling debug symbols*, that would be great.

**Comment by mariobl** [comment] 2017-03-30 08:13
OK, I've now installed the corresponding debuginfo package. When I open it by launching "poedit" in a terminal and open a file via File → Open I get a popup window with the message mentioned above. In the terminal I get:

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-WARNING **: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkToggleButton)

(poedit:22734): Gtk-WARNING **: Negative content height -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkToggleButton)

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-WARNING **: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkToggleButton)

(poedit:22734): Gtk-WARNING **: Negative content height -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkToggleButton)

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
./src/gtk/dataview.cpp(211): assert "gtk_tree_selection_get_select_function(m_selection) == func" failed in CheckCurrentSelectionFunc(): selection function has changed unexpectedly, review this code!
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(poedit:22734): Gtk-WARNING **: gtk_window_set_titlebar() called on a realized window
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(poedit:22734): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

Trace/breakpoint trap (core dumped)


ASSERT INFO:
./src/gtk/dataview.cpp(211): assert "gtk_tree_selection_get_select_function(m_selection) == func" failed in CheckCurrentSelectionFunc(): selection function has changed unexpectedly, review this code!

BACKTRACE:
[1] wxDataViewCtrl::DoSetCurrentItem(wxDataViewItem const&)
[2] wxEvtHandler::TryHereOnly(wxEvent&)
[3] wxEvtHandler::ProcessEventLocally(wxEvent&)
[4] wxEvtHandler::ProcessEvent(wxEvent&)
[5] wxEvtHandler::ProcessPendingEvents()
[6] wxAppConsoleBase::ProcessPendingEvents()
[7] wxApp::DoIdle()
[8] g_main_context_dispatch
[9] g_main_loop_run
[10] gtk_main
[11] wxGUIEventLoop::DoRun()
[12] wxEventLoopBase::Run()
[13] wxAppConsoleBase::MainLoop()
[14] wxEntry(int&, wchar_t**)
[15] __libc_start_main

**Comment by vslavik** [comment] 2017-03-30 08:17
> OK, I've now installed the corresponding debuginfo package

Sigh. You installed it for one of the *dependency libraries*. Did you not notice that the backtrace from Poedit, which you apparently compiled without debug info, is still unchanged?

But never mind that, I overlooked this bit at first:

> ASSERT INFO:
./src/gtk/dataview.cpp(211): assert "gtk_tree_selection_get_select_function(m_selection) == func" failed in CheckCurrentSelectionFunc(): selection function has changed unexpectedly, review this code!

That's an assert in *wxGTK* that pretty clearly says the problem is *in wxGTK code* ("review this code"). Perhaps the best course of action would be to compile wxGTK from WX_3_0_BRANCH first, to see if it fixes it. 

And you *still* didn't provide reproduction information I requested two times now. I'll get back to responding here when you do.

**Comment by mariobl** [comment] 2017-03-30 08:21
What reproduction info do you mean? I've described the way how I open the application and open a po file from the GTK file chooser. That's all.

**Comment by mariobl** [comment] 2017-03-30 08:23
By the way, I've tried to open a few different po files. All of them reproduce the same error.

**Comment by willysr** [comment] 2017-03-30 13:28
i can confirm this behaviour on Slackware 14.2 and current as well
i used wxGTK 3.0.2 compiled from released tarball, not from GIT.

**Comment by vslavik** [comment] 2017-03-30 13:29
That information is already known, but information about wxGTK 3.0 latest is lacking. What *I* know is that the latest wxGTK master does not exhibit this.

**Comment by willysr** [comment] 2017-03-30 13:32
hm... i'm pretty sure most distributions/packagers do not always build from latest master branch and rely on a released tarball.

**Comment by vslavik** [comment] 2017-03-30 14:01
> hm... i'm pretty sure most distributions/packagers do not always build from latest master branch and rely on a released tarball.

Perhaps you could consider not being a smart-ass? Most distributions/packagers can, and regularly do, apply patches too, so that's a pretty ridiculous argument.

To repeat: This seems to be likely a wxGTK bug. If you are interested in seeing it fixed (and if not, why comment?), the first thing to do would be to determine if it is fixed in wxGTK 3.0 already or not. Checking latest 3.0 sources, i.e. what would become the next 3.0.x release, seems prudent and would be helpful.

One more thing: it's not said here, but if I recall correctly, Fedora builds wxGTK against GTK+3. That in particular pretty much demands back-porting patches, because the 2.5 years old 3.0.2 is not good with it, 3.0 latest is better and master much improved. So this may very well be a wxGTK-3.0-old + GTK+3 problem too.

Please understand that I can't very well have installed, and test against myself, all the gazillion distros out there, including their very own custom breakages (Fedora 25 in particular seems to have broken wxGTK rather spectacularly; a few years ago, that was kind of Ubuntu's thing)… I'll get to trying to reproduce your setup eventually, but you're in a better position to do it, and much faster.

**Comment by rffontenelle** [comment] 2017-03-30 14:12
Here some info on my side. Hope it helps.  When possible, I'll try newer wxGTK than what is available on my distro.

Distro: Arch Linux 64-bit

Packages:
- [gdb](https://www.archlinux.org/packages/extra/x86_64/gdb/) 7.12.1-1
- [wxgtk](https://www.archlinux.org/packages/extra/x86_64/wxgtk/) 3.0.2-6 (built against GTK+2)
- [poedit](https://www.archlinux.org/packages/community/x86_64/poedit/) 2.0-1


Test 1:
1. ran `gdb poedit' (see [output](https://github.com/vslavik/poedit/files/882522/gdb-editing.txt))
2. selected edit translation and then opened a PO file
3. the assertion error dialog emerged (see [output](https://github.com/vslavik/poedit/files/882528/assertion-editing-error.txt)), with "stop" and "continue" options
4. if I continue, countless wxBitmap error dialogs are displayed (see [output](https://github.com/vslavik/poedit/files/882530/wxbitmap-error.txt))
5. if I stop, POedit is terminated with SIGTRAP

Test 2:
1. ran `gdb poedit' (see [output](https://github.com/vslavik/poedit/files/882535/gdb-creating.txt))
2. selected created translation and then opened a POT file
3. two wxBitmap error dialogs emerged (see [output](https://github.com/vslavik/poedit/files/882537/wxbitmap-creating-error.txt))
3. two assertion error dialogs emerged (see output of the [first](https://github.com/vslavik/poedit/files/882538/assertion-creating-error.txt) and [second](https://github.com/vslavik/poedit/files/882541/assertion-creating-error-2.txt))
4. if I continue, countless wxBitmap error dialogs are displayed
5. if I stop, POedit is terminated with SIGTRAP

**Comment by vslavik** [comment] 2017-03-30 14:15
> wxgtk 3.0.2-6 (built against **GTK+2**)

So much for that theory… Thanks, so it seems wxGTK 3.0.2 is the only common factor. Should be easier to repro then.

**Comment by willysr** [comment] 2017-03-30 14:27
Well, you can't generalize every packagers will built everything from master branch
Perhaps they do in ARCH or Fedora, but not here (Slackware) since wxGTK is not part of the core packages. It's available in third party repository (SlackBuilds).

Anyway, we have wxGTK3-3.0.2 built against GTK+3

**Comment by mariobl** [comment] 2017-03-30 14:30
Even Arch, which is known for being always up-to-date, ships wxgtk-3.0.2, as Fedora does. I think it's not the best prerequisite for a software to get it into the distributions if it requires the latest git checkout of a library.

**Comment by vslavik** [comment] 2017-03-30 15:17
@rffontenelle Thanks for the logs, this was very helpful, I suspect I know what post-3.0.2 bugfix this depends on. I'll update this bug after some testing. 

@mariobl @willysr No, I don't expect distros to carry latest checkouts. You know full well that I only asked you about it in order to *identify the cause*. Twisting my words like you do is dishonest and absurd - cut it out and stick to actual facts please. 

> I think it's not the best prerequisite for a software to get it into the distributions 

As a side note, accepting wide range of dependencies, as Poedit historically did, is no guarantee either:  Fedora was the last to include it despite dependencies being conservative (including it only when they started being a bit more aggressive), and *still* includes only a half-functional build with major functionality disabled...

**Comment by rffontenelle** [comment] 2017-03-30 16:44
I built poedit 2.0 against wxgtk 3.1.0 (locally built) and none of the above error messages came up.

**Comment by xoan** [comment] 2017-03-31 09:17
Poedit package in Arch Linux official community repo [has been epoched](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/poedit&id=f116adc75b25eb8e21ffec2d15af42ddb67068df) with a comment in the PKGBUILD:

```diff
+# poedit-2.0 depends on wxgtk-3.1+!
```

**Comment by vslavik** [comment] 2017-03-31 09:26
> Poedit package in Arch Linux official community

Complain to Arch Linux.

**Comment by xoan** [comment] 2017-03-31 09:29
> Complain to Arch Linux.

Sorry if you misundertood me. I'm only posting about the solution achieved by Arch Linux while wxgtk is not updated to the version requiered by your application.

In fact, I think this is a nice solution.

**Comment by vslavik** [comment] 2017-03-31 09:35
Err no, requiring an *unstable series* version is not a "solution". It's about the worst imaginable thing to do. 

Sorry, I'm temporarily closing comments here to cut down on the distracting noise. Will update & reopen once I know more about this issue.

**Comment by vslavik** [comment] 2017-04-04 15:57
To summarize, there are two problems:

1. The `CheckCurrentSelectionFunc` assert:
> ./src/gtk/dataview.cpp(211): assert "gtk_tree_selection_get_select_function(m_selection) == func" failed in CheckCurrentSelectionFunc(): selection function has changed unexpectedly, review this code!

2. wxDVC error about wrong type, in two variants:

    1. "Wrong type, required: null but: wxBitmap" 
    2. "Wrong type, required: null but: string"

2i. is fixed in wxGTK in wxWidgets/wxWidgets@4e7f16010039331673ba2f5bde1d90f1e70950e8 and wxWidgets/wxWidgets@34527f747393d712f48199767800e736994ceffc, but I was able to come up with a workaround.

Workarounds for 2ii. is possible too. Currently investigating 1.

Reopening comments. Please only add comments if you discover *new* problems with wxGTK 3.0.2 not listed above; do not post "me too"s or speculations.

**Comment by vslavik** [comment] 2017-04-04 16:51
The CheckCurrentSelectionFunc assert seems impossible to fix in user code — it's a fundamental bug in wxGTK, fixed in wxWidgets/wxWidgets@24c0401e81a4d0206f89b21775adb90fb11bf32a on master and I backported the fix to 3.0 branch as wxWidgets/wxWidgets@ed88188be7e97a0503f3471f7b0452740b732902 now. 

Everything else is fixed now in Poedit itself (will commit right away), but this I don't see how to do — if a certain public function is called twice, wxGTK *will* assert on it, and I don't see how to avoid it. Curiously, this was *not* happening until recently, so I suspect it may have been uncovered by 3015b23205909cf29bb1235a1ccfef614cb4b149 — but I can't revert that, because it's a fix for *another* crash. 

Obviously, the best solution would be to motivate wx to release 3.0.3; second best to patch wxGTK packages (as this must be affecting non-Poedit applications too).

**Comment by willysr** [comment] 2017-04-04 18:28
Since i'm the maintainer of wxGTK3 for SBo project, i can switch to use the latest 3.0 branch.

Any plan to release a new poedit 2.0.1 soon? I think it's easier to state in the release note that you need latest 3.0 branch or 3.0.3 if it ever gets released. This way, downstream will notice and they will also update wxGTK in their own distributions.

**Comment by willysr** [comment] 2017-04-05 01:38
I can confirm that after updating to latext wxWidgets (https://github.com/wxWidgets/wxWidgets/commit/ed88188be7e97a0503f3471f7b0452740b732902) and rebuilding poedit 2.0 + d4eb22c2229ca3f5f9ebe6eebd574e0c040f9ff3 everything works normally again.

**Comment by vslavik** [comment] 2017-04-10 17:09
2.0.1 is out, fixing the wxGTK 3.0.2 issues:
https://github.com/vslavik/poedit/releases/tag/v2.0.1-oss

**Closed by vslavik** 2017-04-10 17:09 UTC
Labels: High, Linux

**Comment by stmc** [comment] 2017-04-11 19:02
2.0.1 has the same problems with wxGTK 3.0.2
Distro: Arch Linux 64-bit

ASSERT INFO:
./src/gtk/dataview.cpp(211): assert "gtk_tree_selection_get_select_function(m_selection) == func" failed in CheckCurrentSelectionFunc(): selection function has changed unexpectedly, review this code!

BACKTRACE:
[1] wxDataViewCtrl::DoSetCurrentItem(wxDataViewItem const&)
[2] wxString wxString::Format<wxString>(wxFormatString const&, wxString)
[3] wxEvtHandler::TryHereOnly(wxEvent&)
[4] wxEvtHandler::ProcessEventLocally(wxEvent&)
[5] wxEvtHandler::ProcessEvent(wxEvent&)
[6] wxEvtHandler::ProcessPendingEvents()
[7] wxAppConsoleBase::ProcessPendingEvents()
[8] wxApp::DoIdle()
[9] g_main_context_dispatch
[10] g_main_loop_run
[11] gtk_main
[12] wxGUIEventLoop::DoRun()
[13] wxEventLoopBase::Run()
[14] wxAppConsoleBase::MainLoop()
[15] wxEntry(int&, wchar_t**)
[16] __libc_start_main

**Comment by rffontenelle** [comment] 2017-04-11 19:12
@stmc wxgtk (from extra) was not patched with fixes from this issue and #369 yet. Problem is in Arch Linux.

**Comment by rffontenelle** [comment] 2017-04-11 19:37
Bug reported against wxgtk: https://bugs.archlinux.org/task/53643

**Comment by vslavik** [comment] 2017-05-02 12:40
[wxGTK 3.0.3 released](http://wxwidgets.blogspot.com/2017/05/303-released.html)

**Comment by rffontenelle** [comment] 2017-05-05 21:24
FWIW, Arch Linux is fine now - packages: wxgtk 3.0.3-1 and poedit 1:2.0.1-2.
