### ISSUE TITLE
Crowdin save don't work

### ISSUE THREAD

**Issue by GalaxyCP** [vslavik/poedit#795] opened 2023-06-11 00:12 UTC
Hi!

When I try to save the translation to Crowdin and then sync, it resets, like I don't translate it

**Comment by vslavik** [comment] 2023-06-11 07:04
Please follow instruction 3 from [this document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) (which GitHub asked you to do when you created this issue):

> Describe the problem exactly, in as much detail as possible. Explain what to do, step by detailed step, in order to see the issue. If you don't have much experience with reporting bugs, read [this very helpful article](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

TIA!

**Comment by GalaxyCP** [comment] 2023-06-11 11:37
hi!
Poedit 3.3.1, macOS 13.2.1 MacBook M1
What I do:
File -> Open from Crowdin
I select my own project with Spanish language
I change translation for few rows. Then I save with File->Save (It shows me syncing with crowding popup and all looks ks good. Like it saved.
Then I check that all is saved, going to crowdin, but nothing changed.

**Comment by vslavik** [comment] 2023-06-11 17:04
Please do read the article I asked you to read and afterwards provide actual reproducible instructions with specifics instead of vague hand-waving like "my project" (I don't see any issue with my project), "change translation" (many ways to do that, including marking it as needs-work, which would of course be unused), "few rows" (so it matters that it is more than one and less than... what, exactly?) etc. 

Please also include some explanation of why you think Poedit's behavior is wrong. That includes pointing to specific string and to its Crowdin-side version.

Crowdin doesn't always use translators' translations immediately. In particular, with proof-reading enabled, your translation is only used after approval, but there are other situations (e.g. due to voting) where new contributions don't take effect. There's nothing in this issue to indicate this isn't the case or the behavior of Poedit or Crowdin is in any way abnormal.

**Comment by vslavik** [comment] 2023-10-19 13:52
Closing as probably bogus for lack of communication.

**Closed by vslavik** 2023-10-19 13:52 UTC
