### ISSUE TITLE
Notes for Translators gone, find unitId non-working

### ISSUE THREAD

**Issue by WienemannCC** [vslavik/poedit#854] opened 2024-08-30 07:49 UTC
After upgrading to version 3.4.4 I no longer see a "Notes for translators" pane in the side bar. This means I cannot copy the unit id but more problematic, when searching for unit ids these are no longer found. This makes working with the translation files very cumbersome. 

Is there a possibility to activate the panel again that I am not seeing?

I'm working with XLIFF v2.0 files on MacOS Sonoma

**Comment by vslavik** [comment] 2024-08-30 07:56
I don't know what you mean by "unit id", or why would you need to "copy" it (and what you mean by that, e.g. copy where), or why do you think "Notes for Translators [is] gone". You present all that as obvious fact and unfortunately provide no evidence and no steps to reproduce. Can you please do it, including attaching any files involved and explaining the details? [This document](https://github.com/vslavik/poedit/blob/master/SUPPORT.md) might help.

**Comment by WienemannCC** [comment] 2024-08-30 08:44
Sorry let me clarify:

With "unit id" I mean the identifier of a translation unit in XLIFF 
`<unit id="primeng_today">
  <segment>
    <source>Today</source>
    <target>Heute</target>
  </segment>
</unit>`

The same entry looks as follows in Poedit v 3.2.2
![today Poedit 3 2 2](https://github.com/user-attachments/assets/761af240-4fcd-4bbc-8e7d-1949857627fb)
The ID is displayed in the "Noted for Translators" section and its text is selectable, should I need to copy it to find its use in the code base. And if I search for "primeng_today" I would find this translation.

In Poedit version 3.4.4 it looks like this:
<img width="1001" alt="today Poedit 3 4 4" src="https://github.com/user-attachments/assets/63dc776c-9dbb-47a7-9414-9e93c8ba8693">
There is no "Notes for Translators" section. The ID has moved next to the source heading and is no longer selectable. If I search for "primeng_today" I will not find the entry.

We use IDs that relate to each other for compound translations and not being able to find entries by id makes this difficult. We remove the `<notes/>` section from the XLIFF files to reduce merge conflicts but even with those in the file v3.4.4 does not display "Notes for Translators"

**Comment by vslavik** [comment] 2024-08-30 10:10
The ID is not a note for translators. The ID is an *ID* and is correctly shown as such. This is an intentional fix and does not mean that *Notes for translator* are "gone". They are shown when there are actual notes on the item.

> We use IDs that relate to each other for compound translations and not being able to find entries by id makes this difficult. 

This is way too brief to make any sense to an outsider, I'm afraid.[^1]

It sounds like you're a corporate/commercial user, so support email would be a better channel to discuss your needs in detail. 

I'm closing this issue as "wontfix/invalid", because the notes work as designed. Whether there are some auxiliary UI improvements that should be made (e.g. making the contexts/ids selectable) are a different topic.

[^1]: IDs are supposed to be unique, so copying and searching for them makes little sense to me; source code references are handled differently than just by IDs in XLIFF; "compound translations"? etc.

**Closed by vslavik** 2024-08-30 10:10 UTC
